### PR TITLE
Start export

### LINKED ISSUE #270: generateExportJson follow-ups
follow-ups to #254 :

* [x] `distortableCollection.avg_cm_per_pixel`
* [x] `generateExportJson` pulls from `distortableCollection.avg_cm_per_pixel`
* [x] startExport ajax call that gets the url for the `status.json` file
* [ ] refactor to get `_getStatusJson`  separated from outer ajax call `_runExport`
* [ ] `distortableCollection.startExport(callbackFn)` with basic `console.log` callback function to show progress every X seconds

### PR DESCRIPTION
**Pull request by sashadev-sky**
Fixes #270  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updates
* [x] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sashadev-sky** [comment]
JSON response: {"status_url":"https://mapknitter-exports-warps.storage.googleapis.com/1559178763/status.json","status":"complete","tms":"public/tms/1559178763/","geotiff":"public/warps/1559178763/1559178763.tif","zip":"public/tms/1559178763.zip","jpg":"public/warps/1559178763/1559178763.jpg","export_id":1559178763,"user_id":null,"size":"3.79191MB","width":"1272","height":"744","start_time":null,"run_time":null,"gem_version":"1.0.7","cm_per_pixel":30.0}

**Comment by jywarren** [comment]
Wow this is great! Is this ready to merge then to start on the UI?

**Comment by jywarren** [comment]
@divyabaid16 did you mention you weren't able to get this working? Did you see my comments here? https://github.com/publiclab/Leaflet.DistortableImage/issues/270#issuecomment-500605485

**Comment by divyabaid16** [comment]
Thank you for notifying me here. I got it working @jywarren. I will start with the UI for multiple image export very soon. 

Thanks!

**Comment by jywarren** [comment]
oh awesome!!!

**Comment by sashadev-sky** [comment]
@divyabaid16 @jywarren and I got a working implementation! Merging it right after the tests are complete :) I will then follow up to refactor it a bit

**Comment by jywarren** [comment]
This is AWESOME

**Pull request merged**
