### PR TITLE
add spinner

### LINKED ISSUE #316: MultiExport follow-ups (just docs now)
follow-ups to #314:

- [ ] show a spinner, and hide it when complete! **pending**: hide when completes
  - loader UI: considering for now just adding animated SVG loader icon to replace Export icon during load
- [x] prompt('Choose a scale in real-world centimeters per pixel, or click OK to use our best guess. Keep this window open to wait for your export to complete.', this._getAvgCmPerPixels()) (i think?) to prompt for a scale, but default to the average size?
- [x] open an issue for the "use the updated status_url value" which i tried to implement but it's not working. We should rejigger the section of code above that tries to match "complete" and the new JSON address. I think if we fix it, things will run a lot smoother!
- [x] and then MK integration!
- [ ] Move documentation from #310 in once figure out how to expose the `startExport` method or confirm working well enough for API exposure

### PR DESCRIPTION
**Pull request by sashadev-sky**
Fixes #316  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [ ] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@jywarren can make it fancier when the exporter starts working right but heres a start! It is technically properly indicative that the export loading never ends..
spin

**Comment by jywarren** [comment]
Hi, thanks Sasha! Reviewing now - and noting that in the gif here, your images are not available on the open web for the exporter to fetch, so that's why it's not completing. But I made a video as I noted in this comment, to try to debug what's going on for you in the export workflow. Thanks!

https://github.com/publiclab/mapknitter/issues/919#issuecomment-522020038

**Comment by jywarren** [comment]
This looks great, good to merge IMO. We can release now or wait until we resolve the single/multiple export issue in https://github.com/publiclab/mapknitter/issues/919

**Comment by jywarren** [comment]
What do you think, @sashadev-sky ? Shall I press merge? Thank you!

**Comment by sashadev-sky** [comment]
@jywarren yes we can merge! It is not connected to the ajax call in any way yet but that will be a quick fix. Ill merge it right now! No bump necessary for this, but itll probably end up in a new release very soon anyway because we have so quite a few PRs to get through

**Pull request merged**
