### PR TITLE
Restore feature

### LINKED ISSUE #396: Revert Bug / Restore idea branchout
Two issues with the revert action:

1) It returns the image back to its natural proportions (the proportions it would have if we added it to the map without specifying corners) - @jywarren perhaps this is actually something we may want and not a bug? But it looks awkward as part of the revert tool. So I say maybe let's fix the revert tool to revert to the proportions set out by the `corners` if given.

and for a part 2, add a new tool `restore` that restores the images back to its natural measurements?

2) each time revert is pressed the image is moved slightly southeast of what it was originally, even though all other aspects are reverted correctly

### PR DESCRIPTION
**Pull request by sashadev-sky**
Fixes #396 (<=== Add issue number here)
 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [ ] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

======================================

- update `revertAction` to `restoreAction`
- bump to "0.14.6"
- make icon gray out before any changes to the image have occurred, and after it is clicked until any changes have occurred again.
- expose `restore` method to API
- general cleaning, remove unused methods

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@VladimirMikulic this PR fixes the `revert` action (i renamed to `restore` - see PR description) we've had lying around for a while. Will remain a non-default tool. Here is a gif what it will look like:


- icon is disabled when no changes to the image are made. 
- it restores the image back to its original proportions / scale, rotation, and location on the map. This is not completely what I wanted - I wanted it to only restore the image as far as proportions and scale but keep the image rotation / location on the map the same. I kept hitting too many edge cases so I dropped it. Lmk if you would want to take a shot at that or if we should just go ahead and merge!

**Comment by VladimirMikulic** [comment]
This does make sense to me. I've always missed this feature. Personally, I would merge this now, and later (if enough interest) would implement a button that would undo the last change (like CTRL + Z in most of the apps).

Now, there is one thing that's odd about this to me. The restore button loses state when we unfocus the image i.e. click somewhere else on the map and then on the image.

undo

Also, why is label "undefined" :)

**Comment by sashadev-sky** [comment]
@VladimirMikulic fixing this will tag you again!! Thanks so much

**Comment by sashadev-sky** [comment]
@VladimirMikulic Ok fixed it up

**Comment by VladimirMikulic** [comment]
Now there is no icon at all and I've build the project.

Screenshot_20200331_012440

**Comment by sashadev-sky** [comment]
@VladimirMikulic Its not a default so it doesn't show up unless you add it on initialization like `actions: [L.RestoreAction, L.LockAction, L.RotateAction],`

**Pull request merged**
