### PR TITLE
resolve trapezoidal distortion issues with project() instead of .latLngToLayerPoint()

### PR DESCRIPTION
**Pull request by jywarren**
WIP fix for part of #301 #85

### CODE REVIEW

**Comment by jywarren** [comment]
@sashadev-sky this was a partial solution, i think? Should we merge this to narrow the issue?

**Comment by sashadev-sky** [comment]
@jywarren 
Woah so glad I decided to look over this tonight! I am pretty sure it completely fixes scale. Walking through it, I think it makes sense.

- We get the center of the image using `latLngToLayerPoint` because that calculation is done relative to the image itself
- but we have to `project` the coordinates so that they are relative to the absolute pixel coordinates, then do the calculations, then `unproject`. Basically because the image lives in the context of the map so any calculations involving projecting it over the map need to use `project`

Going to merge.. and try to write some tests for this 👍Did you say there was a 2nd problem with scale?

**Comment by sashadev-sky** [comment]
@jywarren Also, I was tempted to bump the package # but we are starting to do that more often than not for PRs. I was wondering if that is a common practice for non-breaking bugs for a library that is meant to be used as a dependency? It's a little confusing for me because I understand that some libraries fix the bugs but wait until a batch of updates to release before publishing?

**Comment by jywarren** [comment]
Oh cool! Awesome! I think a few downstream users have reported
scale/distort bugs recently so hopefully this addresses those?

As to releases, I think it's good practice to release at 0.0.x (patch) for
any bugfix. If people want a slower, more stable release schedule, they can
use semver syntax in their package.json to point at only "minor" releases,
so 0.x.0. If you'd like, we can start using `0.0.0-rc1` (i think?) syntax
to offer release candidates for minor releases, before releasing a 0.x.0,
so as to let some bugs shake out first. But it's getting a little granular!

**Comment by sashadev-sky** [comment]
@jywarren I don't feel compelled to use it unless you would like to! Maybe we should revisit this after publishing version 1?

**Comment by jywarren** [comment]
Sure, sounds good!

**Pull request merged**
