### PR TITLE
Rotation API

### PR DESCRIPTION
**Pull request by sashadev-sky**
Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [ ] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

UPDATES:

=====================

- update eslint to recognize es6
- update jshint to recognize es6
- standardize use of `#rotateBy`, `#getAngle`, and `#setAngle` and expose to API
- specs for `#rotateBy`, `#getAngle`, and `#setAngle`
- general cleaning
- fix lint warnings
- add a `rotation` option for `L.distortableImageOverlay` and expose to API
- add `test` script to package.json
- bump version to  "0.13.6"

=====================

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@VladimirMikulic was meaning to push this a while ago when you added the `getAngle` and `setAngle` methods, then cleaned up some other things. Please see PR description and lmk if it's good to merge!

**Comment by sashadev-sky** [comment]
@VladimirMikulic thanks for the quick review, i'll merge now! 

I made that post related to `_calculateProjectiveTransform` btw: https://publiclab.org/notes/sashadev-sky/03-28-2020/if-you-don-t-know-about-georectification#.

Would you be interested in adding anything on? I can add you as a co-author if so, I just need your PL username.

**Comment by VladimirMikulic** [comment]
@sashadev-sky you can just specify my Github profile :)

**Comment by sashadev-sky** [comment]
@VladimirMikulic i think it unfortunately needs to be a PL account, its that new co-author feature on the website. Do you not have a PL account?

**Comment by VladimirMikulic** [comment]
No, I don't. Anyway, it doesn't matter :)

**Comment by sashadev-sky** [comment]
@VladimirMikulic ok np! U should make one tho! Its fun to get involved on there too with coding updates
and SoC proposals.

**Pull request merged**
