### PR TITLE
clean copy of #97 full resolution download

### LINKED ISSUE #83: build in full-resolution image export using webgl-distort
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://publiclab.github.io/community-toolbox/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

https://github.com/jywarren/webgl-distort -- there's example code there! However, we'll need to be able to reference the original quality image -- we're currently doing this now in MapKnitter but we should build this function into this library itself, as it's a common desire: 

https://github.com/publiclab/mapknitter/blob/8d94132c81b3040ae0d0b4627e685ff75275b416/app/assets/javascripts/mapknitter/Map.js#L47-L82

Making this a button in the menu would be great -- button code is here; this excerpt is a single button on the menu:

https://github.com/publiclab/Leaflet.DistortableImage/blob/3714b06bcdae2ff088c1f52c32ec322d120b4962/src/edit/DistortableImage.EditToolbar.js#L12-L25

Any help much appreciated! This could be broken into several pieces for first-timers, possibly.

### LINKED ISSUE #124: need some way to pass in an fullResolutionSrc
To finish #100, we need some way to pass in a `fullResolutionSrc` parameters
 for each image so that we can warp an original image and not the preview, for example on MapKnitter.

Let's figure out how to pass in an extra option and then use it if it exists to do the warping here. Any help appreciated!

### PR DESCRIPTION
**Pull request by jywarren**
Noting that we're moving to the `main` branch, so this'll need to be merged with that.

Based on #97 by @John905 

This needs some way to pass in an `fullResolutionSrc` so that we can warp an original image and not the preview, for example on MapKnitter.

Fixes #124 too!

Fixes #83

### CODE REVIEW

**Comment by jywarren** [comment]
Error is:

```js
   src/edit/DistortableImage.Edit.js
    295 |            if (window && window.hasOwnProperty('warpWebGl')) warpWebGl(
                                                                       ^ Expected '{' and instead saw 'warpWebGl'.
    302 |        }
                  ^ Missing semicolon.
    255 |        var image = overlay._image;
                     ^ 'image' is defined but never used.
    295 |            if (window && window.hasOwnProperty('warpWebGl')) warpWebGl(
                                                                       ^ 'warpWebGl' is not defined.
```

**Comment by jywarren** [comment]
Fixed this, I believe!

**Comment by jywarren** [comment]
Wow, we are /almost/ there! @rexagod this is a different build process and i'm less familiar with it (even though i'm an author of this lib! 😂 ) do you have an idea of how we can include the needed lib besides where i've done it here? 

https://github.com/publiclab/Leaflet.DistortableImage/pull/100/files#diff-0be9d25d2ce091e16baef1e0d91d0cf7R28

```js

Running "jshint:source" (jshint) task
   src/edit/DistortableImage.Edit.js
    298 |                warpWebGl(
                         ^ 'warpWebGl' is not defined.
```

**Comment by jywarren** [comment]
@sashadev-sky are you at all familiar with Karma tests or with `jshint`? I'm not 100% sure but i think this is failing because we're not alerting it of the loading of `warpWebGL` in an external library. But it actually works locally. I'm just trying to problem solve here a bit, maybe you'd have an insight? Thanks!

**Comment by sashadev-sky** [comment]
@jywarren not familiar with them but I’ll take a look today anyway!

**Comment by jywarren** [comment]
Amazing work @rexagod -- thanks for the fixes in https://github.com/publiclab/Leaflet.DistortableImage/pull/129 - pulling them in here.

And i think i fixed the jpg/png error that i also introduced.

**Comment by jywarren** [comment]
Complete!!! Amazing work folks, this is a big one!

**Comment by jywarren** [comment]
Blog post coming soon!

**Comment by jywarren** [comment]
Added to MapKnitter here: https://github.com/publiclab/mapknitter/commit/a5de9bd2f0a6a764396eb2b668153c49e53b44c5

**Pull request merged**
