### PR TITLE
Long press unlock

### LINKED ISSUE #39: long press (touch) to unlock, switch modes
"contextmenu" event: http://leafletjs.com/reference.html

### PR DESCRIPTION
**Pull request by sashadev-sky**
Fixes #39  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [ ] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sashadev-sky** [comment]
Ah no I forgot I was playing with updates on my main. Going to try to reset this

**Comment by sashadev-sky** [comment]
longpress

@jywarren there is not much to see here but this gif demonstrates how a) the context menu no longer comes up on right click of the image b) nothing happens unless the image was locked because its for unlock

**Comment by sashadev-sky** [comment]
@jywarren can i rebase and merge here? my next PR relies on this (long press needs to be off if rotate gesture can happen without being interrupted by context menu)

**Comment by jywarren** [comment]
> will this be very annoying for developers? Or its a common thing to do and they can just use their browsers physical inspect button in dev tools

Unfortunately i think this may be a problem if people want to download the image... :-/ maybe we need to think this through?

**Comment by sashadev-sky** [comment]
@jywarren You mean right-click -> Save image? We have the export functionality to do that too! And I personally have never thought to right click save image.

The context menu will still be available on map right click / long press

**Comment by sashadev-sky** [comment]
@jywarren also sorry not the place for this but, I realized that the material design icons will not work on very old devices (ones that do not accept format `woff2`) because I tried setting it up through css @font-face. I don't like the idea of using a CDN and their npm package is not up to date, so I have converted them to svgs and will add svg sprite. It will be faster and we can use icons from as many libraries as we want too!

I think we should hold off on publishing the drafted release until I get this updated!

**Comment by jywarren** [comment]
> @jywarren You mean right-click -> Save image? We have the export functionality to do that too! And I personally have never thought to right click save image.

Actually i thought save image for the original unwarped image. Again, we could make another means to download this. But it's kind of nice that it "acts like a regular image" on the web. Where are we on nested submenus - that could give us more options on alternative download techniques, if we're dropping the right-click-to-download option that's the browser default?

**Comment by jywarren** [comment]
I was thinking that the multiple image export really makes long-press more necessary. But instead of long-press for unlock (since that's available in the menu, after all), what if we made it long-press to select, which I think is a stronger convention anyways? What do you think, @sashadev-sky ?

**Comment by sashadev-sky** [comment]
@jywarren agreed! good idea! long press for "multi-select"?

**Comment by jywarren** [comment]
Yeah! That'll be great because then people will be able to do multi-select
export from touch devices!

**Comment by sashadev-sky** [comment]
yes amazing. Ok will do this today

**Comment by sashadev-sky** [comment]
@jywarren ok done. Just going to update the README now. I left a tunnel open for you to try it out on a touch device:

https://proud-sheep-46.localtunnel.me

**Comment by sashadev-sky** [comment]
@jywarren this is ready!

**Comment by jywarren** [comment]
Really nice!!!

**Comment by jywarren** [comment]
Great. Can you change the PR title so we remember the change? Thanks!!!

**Comment by sashadev-sky** [comment]
done!

**Pull request merged**
