### PR TITLE
feat: 🎸 place images in the sidebar onto the map

### LINKED ISSUE #1023: allow clicking a sidebar image in MK Lite to add them onto a map for placement
To add an image to the map, the code is:

```js
var img = L.distortableImageOverlay(img_url);
map._imgGroup.addLayer(img);
```

https://github.com/publiclab/mapknitter/blob/3a1e332721c59754fb3ef7638f8169e71953791e/app/assets/javascripts/mapknitter/Map.js#L197-L213

### PR DESCRIPTION
**Pull request by PeculiarE**
Fixes #1023

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updates
* [x] @mention the original creator of the issue in a comment below for help or for a review

### CODE REVIEW

**Comment by PeculiarE** [comment]
**Short demo of image placement in action:**

https://user-images.githubusercontent.com/75625011/192997741-30685485-d0a2-4486-a0ab-a6e4c0cb615e.mp4

**Comment by PeculiarE** [comment]
Okay, so I noticed something.

The collection url used In the previous demo had been used repeatedly while testing the feature and so the images had been cached somewhat in my browser.

Once I used a new url (as seen in the second demo below), images take a significant amount of time to appear on the map after clicking on the `Place on map` button probably because the images are still taking time to load

I'm assuming this significant delay is because of my network connection and should be nonexistent for users with better connection speeds and bandwidth. What do you think @jywarren? And do you mind also testing it from your end so we're sure?

https://user-images.githubusercontent.com/75625011/192997785-96a60c6b-3093-497b-b1b1-bb0fcd7aaa96.mp4

**Comment by jywarren** [comment]
Hi! That's right, and later we could try adding a function to identify
thumbnail images for each, and loading them. But let's not worry just yet!
We could make an issue for someone to work on this later? Thanks!

**Comment by PeculiarE** [comment]
Okay, yeah, that's fine. Thank you!

**Comment by jywarren** [comment]
Just tested this out and it's super. I'll also add a todo for putting a loading spinner on the button, for while it loads!

**Comment by PeculiarE** [comment]
Cool! Thanks Jeff!

**Pull request merged**
