### PR TITLE
Fix toolbar width css bug (chrome)

### LINKED ISSUE #697: Google Chrome toolbar CSS bug
I am seeing only in Chrome that the css for the toolbar is breaking: 

image

Chrome version: 83
platform: macOS catalina

### PR DESCRIPTION
**Pull request by sashadev-sky**
Fixes #697  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [ ] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

Also:

- bump version
- ran `npm audit fix`

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@jywarren @VladimirMikulic don't know what causes this - but i know its new because I see it on my branch [https://sasha.mapknitter.org/examples/index.html](https://sasha.mapknitter.org/examples/index.html) that hasn't been updated in a long time.

**Comment by VladimirMikulic** [comment]
@sashadev-sky yes, it is broken. At the moment width of `leaflet-popup-toolbar` is set to fixed 309px. The funny thing is that it works on 310px. Good to see that you fixed it once and for all (hopefully) with `max-content` property, really handy.
By the way, what happened to Travis?

**Comment by sashadev-sky** [comment]
@VladimirMikulic travis has been failing for a while i have another PR for that #695 
Also didn't mean to commit here again after u reviewed moving that change into a new PR

**Comment by sashadev-sky** [comment]
@VladimirMikulic sorry can u show what you're referring to

**Comment by sashadev-sky** [comment]
also was hoping to merge #695 1st if u have a second to check that out!!

**Comment by VladimirMikulic** [comment]
Sorry about that @sashadev-sky. Here is the image https://i.imgur.com/lrTTOKV.jpg.

**Comment by VladimirMikulic** [comment]
> also was hoping to merge #695 1st if u have a second to check that out!!

Always!

**Comment by sashadev-sky** [comment]
@VladimirMikulic what is the fixed inline style you're referring to?

**Comment by VladimirMikulic** [comment]
@sashadev-sky it is the fixed width :)

f

**Comment by sashadev-sky** [comment]
ooh gotchya. I think this is coming from the leaflet-toolbar library so cant remove it

**Comment by VladimirMikulic** [comment]
@sashadev-sky I guess you are right. I haven't found it in this repo's source code.

**Comment by sashadev-sky** [comment]
I think its coming from this function https://github.com/Leaflet/Leaflet.toolbar/blob/0a080860542dbd1cc5fb3a543f68c4a799d9c88c/src/Popup.js#L52

**Comment by sashadev-sky** [comment]
@jywarren we probably want to make it high priority update this in mapknitter

**Pull request merged**
