### PR TITLE
 Updated DoubleClickLabels.js

### PR DESCRIPTION
**Pull request by TomisinAjayi**
I changed the variables with var to let.

Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [x] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by TomisinAjayi** [comment]
Hello @TildaDares, I just made my first PR

**Review by TildaDares — APPROVED** [review]
Amazing work @TomisinAjayi. Thank you!

**Comment by TomisinAjayi** [comment]
thank you @TildaDares, can I work on other issues?

**Comment by TildaDares** [comment]
Hi @TomisinAjayi, yes you can work on other issues that do not have the FTO label. Thanks!

**Pull request merged**
