### PR TITLE
Issues when DistortableImage is set in a layerGroups (hide and show)

### LINKED ISSUE #440: Can't select after hide the layerGroup ...
Hello !

Still getting the unselectable problem. After hide and show the layerGroup I can't select again my image:

My image is added to a normal layerGroup, and I use it to hide or show a diferent types of elements (cars, bikes, motorbikes, bus, etc in one layer, traffice sings in other, etc)

Ah! And no error in console. Is like the event listener is lost. (not sure how to check)

### LINKED ISSUE #441: >Deleted images come back, but not actives ...
Hello,

After deleting a image used inside a layerGroup, the image come back if you hide and show this layerGroup. But it is not possible to select.

I supose that has some relation with issue #440, probably the solution is the same.

### PR DESCRIPTION
**Pull request by themacboy**
Fixes #440
Fixes #441

Please check example code in debug folder:
layerControl.html

(there I placed too the libraries Im using).

Process to check the issue:
1r. Click in the button with a car in the left side.
2n. A Control panell is showed in right side.
3d. Click un the car image.
4r. Delete the car image from toolbar action.
5e. On the layer control, hide and show the layer: other.

if you avoid pass 4r. you will notice that car image is not selectable again.

Thanks!

p.d: I tryed to use my original code in my app, to be sure to reproduce same error.

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@themacboy checking this out now! 

Also, here is how you can update your `main` branch - every feature branch you create is a snapshot of your local `main` branch, so you need to keep it updated for clean PRs:

**will force your local main branch to an exact copy of upstream main branch**
```bash
$ git remote add upstream https://github.com/publiclab/Leaflet.DistortableImage.git
#make sure you're on your local main branch
$ git checkout main  
$ git fetch upstream
$ git reset --hard upstream/main
#force push your local main branch to your origin main to update that too
$ git push origin main -f
```

typically to update `main` the workflow is to `fetch` regularly, but if you're really diverged the merge conflicts will be very tedious (you're ~30 commits behind)

Then if you wanted to catch up this branch too, only after your local `main` is caught up you can do:
```
$ git checkout layerControl
$ git rebase main
$ git push origin layerControl -f
```

(I think this will be a very rough rebase so don't recommend doing this. If you want specific commits from here you can `cherry-pick` them onto a new branch)

**Comment by sashadev-sky** [comment]
@themacboy this sidebar thing you have going here is so fun i love it

**Comment by themacboy** [comment]
Well still trying to figure how git works hehehe thanks for all help. I was reading in git manual, and sincerelly I hard to understand for me. I will take some video tutorials in my mother language ;)

Just done a rebase on layerControl branch, solved 15 conflicts (no sure why hahaha and how hahaha).

I hope now you can check the problem I found.

**Comment by sashadev-sky** [comment]
@themacboy do you have custom code to re-add the image when switching back to the layer with it? because when I pull the current status of the plugin in (change script tag in html file to <script src="../dist/leaflet.distortableimage.js"></script>) the layer is totally gone but with your version its there just not enabled

**Comment by sashadev-sky** [comment]
you would img.editing.enable() on it to re-enable it

**Comment by themacboy** [comment]
ummm ok then I need to record all images inside every layergroup, and when event on layer group is triggered then I run a function to re-enable all images inside the layer group.

And with the delete images that comes to live again?

**Comment by themacboy** [comment]
> @themacboy do you have custom code to re-add the image when switching back to the layer with it? because when I pull the current status of the plugin in (change script tag in html file to <script src="../dist/leaflet.distortableimage.js"></script>) the layer is totally gone but with your version its there just not enabled

No, layer control do all work. I dint re-add any image.

**Comment by themacboy** [comment]
And with the delete images that comes to live again when layergroup is showed?

A deleted element must be removed, but not, after a deletion, if you hide and show the layer again, the deleted element is there (surpriiiiseeee ! hehehe)

**Comment by sashadev-sky** [comment]
@themacboy hi sorry! I started a new job and wanted to give all my focus to that initially. I reviewed your issue again and found why you are getting this behavior:

```JS
$(".pl_Cro_vehicles").on ("click", function () {
    let dibuix = L.distortableImageOverlay($(this).attr ("src"), {
        height: 150,
        edgeMinWidth: 0,
	crossOrigin: false,
	actions: [L.DragAction, L.RotateAction, L.OpacityAction, L.RevertAction, L.DeleteAction],
	 selected: true,
	mode: "rotate",
	modes: ["rotate, drag"],
	keymapper: false,
	pane: "overlayPane",
	className: "pl_elements pl_vehicles",
     }).addTo(other);		          
})
```

The last line should be:

```JS
addTo(map);
```
So I will close this issue now! Hope your project is going well

**Pull request closed without merging**
