### PR TITLE
Changed let to const in src/edit/DistortableImage.Edit.js

### PR DESCRIPTION
**Pull request by AtulyaJaiswal**
Fixes #1318 

I have updated the document from let to const in src/edit/DistortableImage.Edit.js .
I am sorry for the last comment, please don't mind as I am very new to open source and I was not aware how to write comment, very sorry for this.

### CODE REVIEW

**Comment by cesswairimu** [comment]
Hi @AtulyaJaiswal , thanks for opening this,  could you  please add a link to the  issue this pull request fixes on the description --- On this this line`Fixes #0000` _(replace 0000 with the issue number)_ this will help other contributors while reviewing your changes. It also helps in automatically closing the issue when the pull request is merged. Thanks

**Comment by AtulyaJaiswal** [comment]
@cesswairimu sir, I have updated the comment. 
Sorry for the inconvenience.

**Comment by cesswairimu** [comment]
no worries @AtulyaJaiswal, I meant the issue you are fixing with this PR, i believe it's this one https://github.com/publiclab/Leaflet.DistortableImage/issues/1309 right?  and no biggie but my pronouns are she/her.
Thanks

**Review by cesswairimu — APPROVED** [review]

**Review by cesswairimu — APPROVED** [review]
:tada:

**Comment by AtulyaJaiswal** [comment]
Thank you @cesswairimu for your valuable feedback.

**Comment by segun-codes** [comment]
> Thank you @cesswairimu for your valuable feedback.

@TildaDares, I guess you want to consider merging this now. Many thanks!

**Comment by TildaDares** [comment]
Thank you for the reviews @segun-codes @cesswairimu.

Great work @AtulyaJaiswal 🚀

**Comment by 7malikk** [comment]
Congratulations on your merge @AtulyaJaiswal 🎉 
Good job!

**Comment by AtulyaJaiswal** [comment]
Thank you @segun-codes @TildaDares @cesswairimu @7malikk.

**Pull request merged**
