### PR TITLE
Create first timers issue template.md

### PR DESCRIPTION
**Pull request by faithngetich**
Issue [link](https://github.com/publiclab/plots2/issues/3681#issuecomment-429254015)

### CODE REVIEW

**Comment by jywarren** [comment]
Hi! Could we update this to refer to the local repository instead of plots2? Thanks!!!

**Comment by faithngetich** [comment]
@jywarren Done.

**Comment by jywarren** [comment]
Thank you Faith!!! Please keep us in mind for Summer of Code 2019!!!

**Comment by jywarren** [comment]
Not much just yet, but see https://publiclab.org/notes/warren/01-02-2019/brainstorming-for-summer-of-code-2019 and https://github.com/publiclab/plots2/issues/4585, and we'll hopefully have a call for proposals up in a few weeks!

**Comment by faithngetich** [comment]
Thanks for the update, I'll be sure to take a look.

**Pull request merged**
