### PR TITLE
Hotkeys and major file restructuring

### LINKED ISSUE #360: Aftert unlock set mode is not acurate ...
I have created a distortable element, by default I have set it to "rotate" mode (not scale permited) but after use lock/unlock it return to "scale" or "rotatescale" mode.

I suggest that it is very important to return to his original and default mode "rotate"

thx

### LINKED ISSUE #376: Hotkeys should only be available for present toolbar actions
PART 1: COMPLETE
For ex., if the developer doesn't add the `ToggleRotate` and `ToggleScale` actions, which are not in the toolbar by default, then we shouldn't be able to access them with their hotkeys. 

This would make more sense, and is also important for situations where a developer wants to forbid a certain action.

======= 

PART 2: PENDING
The only part left to resolve is how to make this work for the collection group. If you have one image that has scale in its toolbar, for ex, but another that doesnt, how do you make scale available on only one of them?

=======

### PR DESCRIPTION
**Pull request by sashadev-sky**
Fixes #376  (<=== Add issue number here)
Fixes #360 
- #161 
- #317 
- https://github.com/publiclab/mapknitter/issues/620

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [ ] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

===============

changes:

File Restructuring:
- made a `handles` folder in `edit` folder, which contains `EditHandle.js`, `LockHandle.js`, etc.
- made a `toolbars` folder to hold `DistortableImage.PopupBar.js` and `DistortableImage.ControlBar.js`
- made an `actions` folder in `edit` folder, which follows a similar convention:

| Orig. Name                     	| New Name               	| File                    	| old key     	| new key                                                                      	| old method                                                                                                                             	| new method                                                                 	| comments                                                                                                                                                                                                                                                                   	|
|--------------------------------	|------------------------	|-------------------------	|-------------	|------------------------------------------------------------------------------	|----------------------------------------------------------------------------------------------------------------------------------------	|----------------------------------------------------------------------------	|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|
| `L.EditAction`                 	|                        	| `EditAction.js`         	|             	|                                                                              	|                                                                                                                                        	|                                                                            	|                                                                                                                                                                                                                                                                            	|
| `var ToggleTransparency`       	| `L.OpacityAction`      	| `OpacityAction.js`      	| `t`           	| `o`                                                                            	| `_toggleTransparency`                                                                                                                  	| `_toggleOpacity`                                                           	| Swapped icons so they represent the state currently in.                                                                                                                                                                                                                    	|
| `var ToggleOutline`            	| `L.BorderAction` 	| `BorderAction.js` 	| `o`           	| `b`                                                                            	| `_toggleOutline`                                                                                                                       	| `_toggleBorder`                                                            	| Swapped. Also, image outline refers to something else in Leaflet & most code convention - focusable ring around an el. border is clearer.                                                                                                                                  	|
| `var Delete` and `var Deletes` 	| `L.DeleteAction`       	| `DeleteAction.js`       	| `backspace`   	| `backspace`                                                                    	| methods are the same just  combined plural & singular  version after standardizing  the toolbar API w/  `L.DistortableCollection.Edit` 	| now just uses conditionals to decide if call  should be plural or singular 	|                                                                                                                                                                                                                                                                            	|
| `var ToggleRotate`             	| `L.RotateAction`       	| `RotateAction.js`       	| `CAPS LOCK`   	| `r`  because `CAPS LOCK` as a keybinding is a bug.                               	| `_toggleRotate`                                                                                                                        	| `_rotateMode`                                                              	| it doesn't make sense to toggle every mode with `distort`, or any single mode. Then  icons would need to all toggle to same icon. TB wouldn't make sense. Also overcomplicates  current / future mode API: ex. selecting diff  default mode or just forbidding 'distort'.  	|
| `var ToggleRotateScale`        	| `L.FreeRotateAction`  	| `FreeRotateAction.js`  	| `r`, `d`        	| `f`                                                                            	| `_toggleRotateScale`                                                                                                                   	| `_freeRotateMode`                                                         	| doesn't toggle anymore either                                                                                                                                                                                                                                              	|
| N/A                            	| `L.DistortAction`      	| `DistortAction.js`      	| N/A         	| `d`                                                                            	| N/A                                                                                                                                    	| `_distortMode`                                                             	|                                                                                                                                                                                                                                                                            	|
| `var ToggleScale`              	| `L.ScaleAction`        	| `ScaleAction.js`        	| `s`           	| `s`                                                                            	| `_toggleScale`                                                                                                                         	| `_scaleMode`                                                               	|                                                                                                                                                                                                                                                                            	|
| `var ToggleLock` and `var Locks`               	| `L.LockAction`         	| `LockAction.js`         	| `l`           	| `l`, `u` - `l` only locks, `u` only unlocks, button still toggles                     	| `_toggleLock`                                                                                                                          	| `_togglelockMode`                                                          	|                                                                                                                                                                                                                                                                            	|
| `var Export` and `var  Exports`                  	| `L.ExportAction`       	| `ExportAction.js`       	| N/A         	| `e`                                                                          	|                                                                                                                                        	|                                                                            	|                                                                                                                                                                                                                                                                            	|
| `var EnableEXIF`               	| `L.GeolocateAction`    	| `GeolocateAction.js`    	|             	|                                                                              	|                                                                                                                                        	|                                                                            	|                                                                                                                                                                                                                                                                            	|
| `var Revert`                   	| `L.RevertAction`       	| `RevertAction.js`       	|             	|                                                                              	|                                                                                                                                        	|                                                                            	|                                                                                                                                                                                                                                                                            	|
| `var ToggleOrder`              	| `L.StackAction`  	| `StackAction.js`  	| `j`, `k`    	| `q`, `a`  now q will only  stack up / `a`  will only stack  down, not random 	|                                                                                                                                        	|                                                                            	|                                                                                                                                                                                                                                                                            	|

- updated Keymapper accordingly 

- In a past PR, when I added an `L.DistortableCollection.Edit` #335, this allowed me to align the Tool / Action APIs in `L.DistortableCollection` and `L.DistortableImageOverlay.`.

   - `L.DistortableCollection` now shares its tools with `L.DistortableImageOverlay`. `L.ExportAction`, `L.DeleteAction`, and `L.LockAction` are all written to work for single and multi interface to avoid having to write duplicate tools.
  - was able to get rid of `var Exports`, `var Deletes`, and `var Locks`. 
  - the only one `L.DistortableCollection` still doesn't share is `var Unlocks`, which is now `L.UnlocksActions` (kept it in `ControlBar` file instead of giving it its own)

- bump version to `0.8.0`

- distort is finally its own toolbar action, so and most icons aren't toggle actions. 

UI Improvements:
- mode tools are highlighted according to their corresponding color when active

![ui 2](https://user-images.githubusercontent.com/41092741/63395071-81afcd80-c390-11e9-8131-2a77f706d41f.gif)

Bug Fixes:
- Keybindings are only present on individual images that have the corresponding toolbar action. Same with collection group.
- `Rotate` keybinding changed from `CAPS LOCK` to `r`
- you can **switch out of lock mode via keybindings for a **mode** or clicking on another mode**
- on image `doubleclick`, it will iterate through all available modes in order. 
- after exiting out of lock mode, you will be on the mode that you originally set as your default (or 'distort' - our default)
- README updates

Pending:

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@rexagod i'm gonna finish off the 2nd half for #376!

**Comment by sashadev-sky** [comment]
@jywarren @rexagod this is ready for review! This fixes the keybindings issue where they don't match with the actual tools in the images individual / collective toolbars, and addresses #161 in an organized way!

**Comment by sashadev-sky** [comment]
ill update docs if you guys like this

**Comment by sashadev-sky** [comment]
@jywarren note that I went about this a little differently than in #317. Primarily because the actions work for single and multiple instances of images with conditionals

**Comment by sashadev-sky** [comment]
@jywarren this is ready for merge (just needs rebase) and approved by rexagod! But I will hold on that because it is a big change - I made a markdown table in the PR description so you can easily follow the changes and new structure. Let me know your thoughts! For now going to revert my focus on getting MK to work

**Comment by sashadev-sky** [comment]
@jywarren just wanted to follow up here because this PR makes some big changes!

**Comment by jywarren** [comment]
Hi Sasha, i'm so sorry, I am a bit overloaded with final GSOC reviews going
in today. I will take a look as soon as possible. Thank you!

**Comment by sashadev-sky** [comment]
No problem! I thought they were due on Monday?! I haven’t added my reviews yet.

**Comment by jywarren** [comment]
They are -- but as monday is a holiday i'm making sure they are all
submitted and will add any final input just before deadline. Thanks!

**Comment by sashadev-sky** [comment]
@jywarren ok got it!

**Comment by themacboy** [comment]
Hello @sashadev-sky, I tryed to figure how to add my Drag only mode in this PR. I set a few changes, but im not sure if Im doing all correctly.

For example, i don't understand how to add my 4 dot start icon in the L.ToolbarIconSet. (sorry not sure how this draw code works).

I hope I helped and not make your work more difficult.

**Comment by sashadev-sky** [comment]
@themacboy sorry I will checkout your work soon :) working on a critical problem with setup downstream right now.

Have you taken a look at this wiki?
https://github.com/publiclab/Leaflet.DistortableImage/wiki/SVG-Icon-System

**Comment by jywarren** [comment]
I wanted to say i reviewed this finally and I love it - much clearer naming conventions, use of global namespace, etc. Great work!

**Comment by sashadev-sky** [comment]
@jywarren yes breaking. but need to rip the band aid off on that I guess. Not breaking for MK. 
Woah so happy I made that table lmao. I would have no recollection what I changed here

**Comment by sashadev-sky** [comment]
this is a really important pr so glad to get it approved finally. will prepare it for merge now

**Comment by sashadev-sky** [comment]
are small breaking changes so ill open a pr in MK right after merging this to address those

**Comment by sashadev-sky** [comment]
@jywarren @rexagod heres a final demo of whats goin on here:

1. All the modes are placed next to each other and their keybindings are sequential on the keyboard and easy to work with. In order:
scale: `s`, distort: `d`, rotate: `r` freerotate: `f` lock: `l`

2. Its a little zoomed out but you will see when you get to lock mode, all non-mode actions will be greyed out, indicating they are disabled. and have no pointer events and auto cursor. They will not respond to click or keybindings.
- the exception to this as has been requested before is `L.ExportAction` will still work even in lock mode
- the purpose of this is to clarify what can and cannot be done in lock mode. Bascially, in lockmode all you can really do is just switch the mode to start doing other stuff. you don't have to first toggle the lock to switch like before, which i agree was confusing.

3. Double clicking on the image will iterate through all the modes sequentially. 

exampl

**Comment by sashadev-sky** [comment]
@jywarren really proud of this refactor looks so much more aesthetic

https://github.com/publiclab/Leaflet.DistortableImage/blob/d1cd4ff6ebf4763274d95f60335ca24e8f2ce051/src/edit/DistortableImage.Edit.js#L289-L313

**Pull request merged**
