### PR TITLE
Export ordering fix

### PR DESCRIPTION
**Pull request by jywarren**
Fixes as follow-up to #316 #318

### CODE REVIEW

**Comment by jywarren** [comment]
Published to `npm` as `v0.5.2`! cc @sashadev-sky

**Comment by sashadev-sky** [comment]
@jywarren I am updating our [release draft](https://github.com/publiclab/Leaflet.DistortableImage/releases) just because its still a good way to keep track of updates and credit people. I was wondering if this was a bug fix? Why do  we want to export the images in reverse order?

**Comment by jywarren** [comment]
Ah it was just that the exporter API wanted it bottom first, not top first as we'd sent it. So, just a mismatch in API convention, not an actual order change! Thanks! And we can publish a release if you want, this was a lot of changes!

**Comment by sashadev-sky** [comment]
@jywarren just submitted the release summaries up to 0.6.1 - https://github.com/publiclab/Leaflet.DistortableImage/releases/tag/v0.6.1

**Comment by jywarren** [comment]
Awesome!!!

**Pull request merged**
