### PR TITLE
Update exportaction.js to have ES6 syntax

### LINKED ISSUE #1042: Update method creation syntax to ES6 `ExportAction.js`
### 🆕🐥☝ First Timers Only.

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

[About First Timers Only](http://www.firsttimersonly.com/).

### 🤔 What you need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below.

  Once claimed we add you as contributor to this repository.

- [ ] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this issue

- [ ] 📝 **Update** the file [\src/edit/actions/ExportAction.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src%2Fedit%2Factions%2FExportAction.js) in the `Leaflet.DistortableImage` repository (press the little pen Icon) and edit the line as shown below.

```diff
@@ -1,6 +1,6 @@
 L.ExportAction = L.EditAction.extend({
   // This function is executed every time we select an image
-  initialize: function(map, overlay, options) {
+  initialize(map, overlay, options) {
     var edit = overlay.editing;
     var tooltip;
 
@@ -26,7 +26,7 @@ L.ExportAction = L.EditAction.extend({
     L.EditAction.prototype.initialize.call(this, map, overlay, options);
   },
 
-  addHooks: function() {
+  addHooks() {
     var edit = this._overlay.editing;
 
     if (edit instanceof L.DistortableImage.Edit) {
@@ -71,47 +71,47 @@ L.ExportAction = L.EditAction.extend({
     }, this);
   },
 
-  resetState: function() {
+  resetState() {
     this.renderDownloadIcon();
     this.isExporting = false;
     this.mouseLeaveSkip = true;
   },
 
-  attachMouseEventListeners: function(element) {
+  attachMouseEventListeners(element) {
     element.addEventListener('mouseenter', this.mouseEnterHandler);
     element.addEventListener('mouseleave', this.mouseLeaveHandler);
   },
 
-  detachMouseEventListeners: function(element) {
+  detachMouseEventListeners(element) {
     element.removeEventListener('mouseenter', this.mouseEnterHandler);
     element.removeEventListener('mouseleave', this.mouseLeaveHandler);
   },
 
-  handleMouseEnter: function() {
+  handleMouseEnter() {
     this.renderCancelIcon();
   },
 
-  handleMouseLeave: function() {
+  handleMouseLeave() {
     if (!this.mouseLeaveSkip) {
       this.renderExportIcon();
     } else {
       this.mouseLeaveSkip = false;
     }
   },
 
-  renderDownloadIcon: function() {
+  renderDownloadIcon() {
     L.IconUtil.toggleXlink(this._link, 'get_app', 'spinner');
     L.IconUtil.toggleTitle(this._link, 'Export Images', 'Loading...');
     L.DomUtil.removeClass(this._link.firstChild, 'loader');
   },
 
-  renderExportIcon: function() {
+  renderExportIcon() {
     L.IconUtil.toggleXlink(this._link, 'spinner');
     L.IconUtil.toggleTitle(this._link, 'Export Images', 'Loading...');
     L.IconUtil.addClassToSvg(this._link, 'loader');
   },
 
-  renderCancelIcon: function() {
+  renderCancelIcon() {
     L.IconUtil.toggleXlink(this._link, 'cancel');
     L.IconUtil.toggleTitle(this._link, 'Cancel Export', 'Loading...');
     L.DomUtil.removeClass(this._link.firstChild, 'loader');
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions

Leave a comment below!

This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).

### PR DESCRIPTION
**Pull request by toshitapandey**
Fixes #1042 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [ ] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by toshitapandey** [comment]
@TildaDares - This is done. Please review this PR.

**Review by TildaDares — APPROVED** [review]
Amazing work @toshitapandey. Thank you!!

**Comment by toshitapandey** [comment]
@TildaDares - any chance that this can be added to hacktoberfest?

**Comment by TildaDares** [comment]
Of course, I can add a label that signifies it was for hactoberfest.

**Comment by toshitapandey** [comment]
Thanks a ton!

**Comment by TildaDares** [comment]
Congratulations on merging your PR @toshitapandey 🎉🎉

**Comment by toshitapandey** [comment]
@TildaDares - Thanks a ton! 
My twitter handle is toshitapandey

**Comment by toshitapandey** [comment]
Hey @TildaDares!
Hope you are doing good. 

The spelling of the `hacktoberfest-accepted` label is wrong. Could you please correct it?

**Comment by TildaDares** [comment]
I've updated it @toshitapandey. Is that okay?

**Pull request merged**
