### PR TITLE
Andro genius codes patch 2 fix for drag and drop feature for export.html

### PR DESCRIPTION
**Pull request by AndroGenius-codes**
Fixes ##998 (<=== Add issue number here)

[drag and drop fix.webm](https://user-images.githubusercontent.com/70571088/196302521-ced2f80a-4638-4913-bf28-4c84955f8977.webm)

**this is it what it looked like before**
export page

NB: still fine tuning the multiple drag and drop feature

### CODE REVIEW

**Comment by AndroGenius-codes** [comment]
@jywarren @cesswairimu @TildaDares @PeculiarE .
sorry for tagging all of you. just hoping one of you is free to review

**Comment by jywarren** [comment]
Hi @AndroGenius-codes - this looks very cool! I wonder if you could implement it in archive.html instead? That's where our "MapKnitter Lite" implementation will live. 

The other thought i had was, what if you could simply drag images onto the screen, and they could appear as distortable images directly? The way it used to work in MapKnitter is show here:


https://user-images.githubusercontent.com/24359/196316972-7c2c4d67-fa08-46e1-8542-86ff98be60a7.mov

But I'm not even sure it needs to have the popup window to confirm "place" for the image... it could just appear on the map, and the alert could appear. 

But notice how when you hover the dragged image over the map, the edge of the map highlights, so you know it's offering to let you drag it in. We could even show the warning message about local only images there! See how in Gmail, it also shows text when you drag an image over:

Screen Shot 2022-10-17 at 9 55 35 PM

What do you think? Could the whole map show a "drag and drop" message as you drag an image over?

**Comment by AndroGenius-codes** [comment]
> Hi @AndroGenius-codes - this looks very cool! I wonder if you could implement it in archive.html instead? That's where our "MapKnitter Lite" implementation will live.
> 
> The other thought i had was, what if you could simply drag images onto the screen, and they could appear as distortable images directly? The way it used to work in MapKnitter is show here:
> 
>  Screen.Recording.2022-10-17.at.9.53.02.PM.mov 
> But I'm not even sure it needs to have the popup window to confirm "place" for the image... it could just appear on the map, and the alert could appear.
> 
> But notice how when you hover the dragged image over the map, the edge of the map highlights, so you know it's offering to let you drag it in. We could even show the warning message about local only images there! See how in Gmail, it also shows text when you drag an image over:
> 
> Screen Shot 2022-10-17 at 9 55 35 PM
> 
> What do you think? Could the whole map show a "drag and drop" message as you drag an image over?

This sounds cool. I think I can implement it. Let me get work on it

**Comment by AndroGenius-codes** [comment]
> @jywarren @cesswairimu @TildaDares @PeculiarE . sorry for tagging all of you. just hoping one of you is free to review


does this look like what you have in mind? i still haven't finished. just wanted to know if i am on the right track
[Untitled_ Oct 19 2022 10_13 AM.webm](https://user-images.githubusercontent.com/70571088/196759709-d41d685b-3da2-4568-ab6e-7a3eadd7ae18.webm)

**Comment by jywarren** [comment]
Hi @AndroGenius-codes -- thank you, this is really nicely designed! My thought was, however, that people could drag an image directly from their desktop onto the map, so we would skip the step where you select an image using a button. There is code for this kind of dragging from the filesystem directly, in this example:

https://jywarren.github.io/bookletize.js/

The code driving this is here:

https://github.com/jywarren/bookletize.js/blob/6ab0280805b89e7639339897f8ecc0022f38dc46/dist/bookletize.js#L71-L116

We could attach it to the entire map element, what do you think?

**Comment by AndroGenius-codes** [comment]
understood. i did a better fix at issue  #1236.

i had to edit it on a separate branch

**Comment by jywarren** [comment]
OK, moving to #1236 then, thank you!

**Pull request closed without merging**
