### PR TITLE
Update BoxCollector.js

### PR DESCRIPTION
**Pull request by Munnachienyi**
Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [x] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by Munnachienyi** [comment]
https://github.com/publiclab/plots2/issues/11105

**Comment by onujoy14** [comment]
I claim this

**Comment by Munnachienyi** [comment]
@TildaDares can you review this please

**Review by TildaDares — APPROVED** [review]
Great job @Munnachienyi. Thank you!

**Comment by TildaDares** [comment]
Amazing work @Munnachienyi. Thank you!

**Comment by Munnachienyi** [comment]
you welcome @TildaDares ,i would like to be assigned another FTO issue

**Comment by TildaDares** [comment]
Hi @Munnachienyi, contributors are only allowed to work on one FTO issue. You can look for non-FTO issues to work on or create issues for other contributors. Thank you!

**Pull request merged**
