### PR TITLE
Change rgb to rgba

### PR DESCRIPTION
**Pull request by adriankwiat**
Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [ ] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@adriankwiat awesome catch, thanks for the PR. 

I had actually thought that rgb could be used with a 4th parameter and it made no difference, but after your PR I did some investigating and found that it doesn't render properly on the iPad mini (2012). 🤷‍♀️

Did you find a similar problem on your device or you just saw a syntax error to fix?

**Comment by sashadev-sky** [comment]
@adriankwiat @rexagod oh wow it wasn't the old ipad, it just doesn't work in safari at all (on MacOS mojave latest version). It flags it an invalid property. Interesting because in Chrome and Firefox they both show its valid. Any idea why this difference?

**Comment by adriankwiat** [comment]
@sashadev-sky when I imported file to SASS I got a compilation error.

**Comment by sashadev-sky** [comment]
the merits of sass

**Comment by sashadev-sky** [comment]
thank you!

**Pull request merged**
