### PR TITLE
update L.icon initializers syntax

### LINKED ISSUE #297: Update L.Icon initializers to use class factory syntax
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/Leaflet.DistortableImage/issues) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

**What's supposed to happen:**

From the official [Leaflet docs](https://leafletjs.com/reference-1.0.0.html):
<blockquote>

Class Factories
You may have noticed that Leaflet objects are created without using the new keyword. This is achieved by complementing each class with a lowercase factory method:

new L.Map('map'); // becomes:
L.map('map');

</blockquote>

**What actually does happen:**

We use Leaflet's built-in `L.Icon` to initialize our handles, but we don't take advantage of their suggested class factory syntax. Let's update the code in the files indicated below.

## Solution

**Where to find the relevant lines of code**: 

Remove the `new` keyword from the following code blocks and update `L.Icon` to `L.icon` :

1) 
https://github.com/publiclab/Leaflet.DistortableImage/blob/ec788da5a7399e119e6a78e9ba7dbf025795e9b5/src/edit/DistortHandle.js#L4-L9

Bonus - for points 2 - 5: let's _also_ move the closing bracket down a line so it's directly in front of the closing parenthesis (like we see in the previous code block)

2) 
https://github.com/publiclab/Leaflet.DistortableImage/blob/ec788da5a7399e119e6a78e9ba7dbf025795e9b5/src/edit/LockHandle.js#L4-L8

3) 
https://github.com/publiclab/Leaflet.DistortableImage/blob/ec788da5a7399e119e6a78e9ba7dbf025795e9b5/src/edit/RotateHandle.js#L4-L8

4)
https://github.com/publiclab/Leaflet.DistortableImage/blob/ec788da5a7399e119e6a78e9ba7dbf025795e9b5/src/edit/RotateScaleHandle.js#L4-L8

5) 
https://github.com/publiclab/Leaflet.DistortableImage/blob/ec788da5a7399e119e6a78e9ba7dbf025795e9b5/src/edit/ScaleHandle.js#L4-L8

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/Leaflet.DistortableImage](https://github.com/publiclab/Leaflet.DistortableImage)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, if there's an additional checklist provided for getting it merged, get those boxes checked off. Either way, mention me @sashadev-sky for a review.

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

### PR DESCRIPTION
**Pull request by ajmorozoff**
update L.icon initializers to class factory syntax, removing new keyword
 
Fixes #0297 (<=== Add issue number here) https://github.com/publiclab/Leaflet.DistortableImage/issues/297

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updates
* [x] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by ajmorozoff** [comment]
Reviewer @sashadev-sky

**Comment by sashadev-sky** [comment]
@ajmorozoff thank you this is perfect! The last thing you'll need to do is generate a build file and commit it here too. if you run `grunt` it should update your dist 👍

**Comment by ajmorozoff** [comment]
Only file that updated was package-lock.json
Not sure if that's right?
Committed here

**Comment by sashadev-sky** [comment]
@ajmorozoff We don't commit `package-lock.json` unless we're making explicit changes to a gem. So you're going to want to check it out. You can't just delete it because that's still a file modification. Instead:

1) Switch to this feature branch if you're not already on it still:
`$ git checkout <featurebranch>`

2) Overwrite the modified file with the file from our main branch. You can use your origin main if its clean (you didn't make any changes to package-lock.json there):

`$ git checkout origin/main -- package-lock.json`

3) Commit and push:

```
$ git commit -m "Removed a modified file from pull request"
$ git push origin <featurebranch>
```

For dist files, you tried running `$ grunt` on the feature branch and there were no updates? You should see this view when you run it:

Screen Shot 2019-06-07 at 10 20 34 PM

Note at the bottom it says "running concat:dist"

alternatively you can try forcing the rebuild by running `$ grunt concat:dist`

**Pull request merged**
