### PR TITLE
Update L.ScaleHandle method creation to ES6 syntax

### LINKED ISSUE #605: Update L.ScaleHandle method creation to ES6 syntax
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/Leaflet.DistortableImage/issues) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

We just added support for ES6 in our library, and would like to start transitioning our code to use this syntax.

Let's update the method creation syntax in the `src/edit/handles/ScaleHandle.js` file from ES5 to ES6.

## Solution

**Where to find the relevant lines of code**: 

For the 2 functions in `src/edit/handles/ScaleHandle.js`, remove the `function` keyword and attach the method arguments to the method name instead.

Here is an example of how this will look for a different method. These ones should follow suit:

ES5
```JS
radiansToDegrees: function(angle) {
  return (angle * 180) / Math.PI;
},
```

ES6
```JS
radiansToDegrees(angle) {
  return (angle * 180) / Math.PI;
},
```

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/Leaflet.DistortableImage](https://github.com/publiclab/Leaflet.DistortableImage)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, if there's an additional checklist provided for getting it merged, get those boxes checked off. Either way, mention me @sashadev-sky for a review.

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

### PR DESCRIPTION
**Pull request by theodumont**
Fixes #605 

Don't hesitate to tell me if there is a problem somewhere!

### CODE REVIEW

**Comment by theodumont** [comment]
Hello, no problem! The fact is I deleted my fork of the project. Am I still able to commit the `dist` file in some way? I wasn't able to find an answer to this question online.

**Comment by sashadev-sky** [comment]
@theodumont you would still be able to, but you will only get anonymous credit for your contribution. 

You also could just fork the repo, and open a new branch / PR. I wouldn't mind this because it's my fault for not getting back to you for so long!

Up to you.

**Comment by theodumont** [comment]
No problem, I should have kept the fork!
I forked the repo again. After a `npm run build`, I'm trying to commit my changes in `dist` and `ScaleHandle.js`, but the pre-commit hook fails and I cannot see why.

```bash
husky > pre-commit (node v12.18.2)

> leaflet-distortableimage@0.17.7 linter C:\...\Leaflet.DistortableImage
> eslint .


C:\...\Leaflet.DistortableImage\.eslintrc.js
   3:18  error  Missing trailing comma                        comma-dangle
   8:34  error  Missing trailing comma                        comma-dangle
  11:19  error  Missing trailing comma                        comma-dangle
  30:37  error  There should be no space after '{'            object-curly-spacing
  30:59  error  There should be no space before '}'           object-curly-spacing
  31:5   error  Inconsistently quoted property 'curly' found  quote-props
  34:26  error  There should be no space after '{'            object-curly-spacing
  34:47  error  There should be no space before '}'           object-curly-spacing
  40:4   error  Missing trailing comma                        comma-dangle

✖ 9 problems (9 errors, 0 warnings)
  9 errors and 0 warnings potentially fixable with the `--fix` option.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leaflet-distortableimage@0.17.7 linter: `eslint .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leaflet-distortableimage@0.17.7 linter script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\...\npm-cache\_logs\2020-07-17T18_47_31_797Z-debug.log
husky > pre-commit hook failed (add --no-verify to bypass)
```

could you help me with this? Thank you very much!

**Comment by sashadev-sky** [comment]
hey! if you read the last line, you see that you can just run `--no-verify` to bypass the pre-commit handle. The errors don't correspond to your changes, so I will clean them up later.

**Comment by theodumont** [comment]
Ok, perfect! I'll open a new PR.

**Comment by sashadev-sky** [comment]
closing moved to #691

**Pull request closed without merging**
