### PR TITLE
ADD: setAngle() method

### LINKED ISSUE #102: Get rotate angle of image layer
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more**

Hello

How do I can get / set rotation degree for an image layer.
Something like: image.getRotate() / image.setRotate(45)
I can't find anything, please help me.

Thanks

### PR DESCRIPTION
**Pull request by VladimirMikulic**
The method accepts an angle in degrees and sets element's rotation to be
that angle. It can also accept negative degrees.

[Demo](https://streamable.com/ydogf)

Resolves #102

@sashadev-sky @jywarren @SidharthBansal could you review this, please?

### CODE REVIEW

**Comment by jywarren** [comment]
This is awesome. Would you be interested in making a simple test for this? Thank you!

**Comment by VladimirMikulic** [comment]
@jywarren this cannot be tested because `getAngle()` method uses L.DomUtil.getStyles function which is  `undefined`(not accessible) in tests. I could refactor `getAngle()` and then add tests in separate PR.

Can we get this feature merged?

**Comment by jywarren** [comment]
Sure, we'll go ahead and merge this then; it's an addition rather than a change in any case. Would you be able to open a new issue describing what'd have to happen to get a test for this? Thank you!

**Comment by VladimirMikulic** [comment]
@jywarren thanks! I could open the issue, that's not the problem, but the problem is in tests.
In browser `getAngle` works flawlessly, but in the tests, it always returns 0.
It might be related to the fact that we use PhantomJS in tests instead of a "real" browser.

We'll need to debug this before we could write a test for this.

**Comment by jywarren** [comment]
OK, that's fine - can you open an issue with that text? That way someone
may come along who can help us resolve it. Thank you!

**Comment by VladimirMikulic** [comment]
@jywarren I have some news for you.
I was right, it was an issue with PhantomJS, `L.DomUtil.getStyles` is accessible when browser is ChromeHeadless, but inaccessible in PhantomJS. On the other hand, 3 tests fail on ChromeHeadless.

I've noticed that `rotation` property is correct although `getAngle` returns 0.
Maybe our test could be:
```javascript
describe('#setAngle', function() {
    it('should set image angle to 90 deg', function () {
      overlay.setAngle(90)
      expect(overlay.rotation).to.equal(-90);
    });
  });
```
This would require fixing 3 failing tests, and switching to ChromeHeadless.
Also, PhantomJS is not [active](https://phantomjs.org/) anymore. 
What do you think? Thanks.

**Comment by jywarren** [comment]
That would be great -- shall we make a GCI issue for it, do you think? Are
you participating in GCI? Just checking!

**Comment by VladimirMikulic** [comment]
Yes, I am participating in GCI and we could make GCI task out of this.
Could you also please provide your opinion on https://github.com/publiclab/plots2/pull/7086.
It's form validation, very important :)

Thanks.

**Comment by SidharthBansal** [comment]
Vladimir is a gci student

**Comment by SidharthBansal** [comment]
Vladimir you can take the task which Jeff wants a GCI task if you want

**Comment by VladimirMikulic** [comment]
Thanks @SidharthBansal, I've noticed that you approved the task on GCI dashboard.
Did you see my comments in the PR? 
Could you tell what you think?

Thanks.

**Comment by SidharthBansal** [comment]
Hi I approved it when Jeff was at holidays and you have completed it. You
were in blocked state(/free) so I wanted you to utilize your time
productively in his and Sashas absence.
You will get points for only completed tasks. Kindly complete your tasks to
get their points.

**Comment by SidharthBansal** [comment]
I have specialisation in MK SWB and Plots. For LDI please refer other
mentors.
Thanks

**Comment by sashadev-sky** [comment]
@VladimirMikulic this is so great!! 
Also I know that the Leaflet js library still uses phantomJS so i'm not sure we need an update unless you really want to make a case for it.
And sounds good for the `rotation` property. I'll open a new Github issue for that now and upload it to the GCI dashboard!

**Comment by sashadev-sky** [comment]
actually wait, the `rotation` property does not work correctly! I will update it to use your `getAngle` method. For the tests then we'd have to sort of polyfill `L.DomUtil.getStyle`? Anyway for GCI credit this is complete so don't worry about it for now

**Comment by VladimirMikulic** [comment]
@sashadev-sky we can either polyfill `L.DomUtil.getStyle` or switch to ChromeHeadless.

**Comment by sashadev-sky** [comment]
@VladimirMikulic I could be misunderstanding the problem you are running into but I think the issue might be that the css `transform` property  throws the error, not the method, and it can be fixed by updating the code to `var matrix = this._image.style[L.DomUtil.TRANSFORM]`. Lmk!

**Comment by VladimirMikulic** [comment]
@sashadev-sky yes, `this._image.style[L.DomUtil.TRANSFORM]` doesn't throw errors in test, but the returned angle from `getAngle` still stays 0.

**Pull request merged**
