### PR TITLE
updating file from es5 to es6

### PR DESCRIPTION
**Pull request by abdelquodr**
Fixes #620  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updates
* [x] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by abdelquodr** [comment]
@TildaDares, kindly check my PULL REQUEST. I have updated the file from es5 to es6. Thanks

**Review by TildaDares — APPROVED** [review]
Amazing work @abdelquodr. Thank you!

**Comment by TildaDares** [comment]
Congratulations on merging your PR @abdelquodr 🎉

**Comment by abdelquodr** [comment]
@Thabks @TildaDares 
I'm open to another issue. can I add my name up again to the list of people expecting issue ?

**Comment by TildaDares** [comment]
Hi @abdelquodr, only first-timers are added to the list. You can work on other non-FTO issues or create issues for other people to work on.

**Pull request merged**
