### PR TITLE
Core generateExportJson function

### LINKED ISSUE #203: Way to start a cloud-based full-res export of a DistortableCollection
We should do this in 2 parts: 

## Core `generateExportJson` function -       ☑️

`distortableCollection.generateExportJson()` would return an `export.json` from a selected image collection 

The `export.json` format would follow: https://github.com/publiclab/mapknitter-exporter-sinatra/pull/1#issuecomment-478173823 - 

`cm_per_pixel` is centimeters of real-world dimension, per pixel of image
cm can be calculated in Leaflet using the distance between the top left and top right corners

Distance conversion utilities: https://leafletjs.com/reference-1.4.0.html#crs-distance

## UI

Part 2 is a bare-bones UI (we'll refine later) to submit this `export.json` to a remote server; maybe a button in the toolbar which opens a bootstrap modal for now?

This will all link up with our new exporter system in https://github.com/publiclab/mapknitter/issues/298

### PR DESCRIPTION
**Pull request by sashadev-sky**
Fixes #203  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updates
* [x] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@jywarren is this what was needed for part 1 of the referenced issue?

**Comment by jywarren** [comment]
If you're ready we can merge this and then make a more specific wrapper function that actually submits it to export.mapknitter.org, what do you think?

**Comment by jywarren** [comment]
Exciting!!!

**Comment by sashadev-sky** [comment]
@jywarren It returns a JSON string into the console. Is that okay? I tested it! Here is a screenshot: I saved the featureGroup on the window for testing and here you can see 3 images are selected, and the corresponding JSON data for them is returned in the console

Screen Shot 2019-05-20 at 2 10 28 AM

**Comment by sashadev-sky** [comment]
@jywarren its a little hard to read, but I followed this structure from the original issue: 

```
{
  'images': [
    {
    "cm_per_pixel": 4.99408,
    "nodes": [ 
      {"lat":"-37.7664063648","lon":"144.9828654528"}, // id is also optional here
      {"lat":"-37.7650239004","lon":"144.9831980467"},
      {"lat":"-37.7652020107","lon":"144.9844533205"},
      {"lat":"-37.7665844718","lon":"144.9841207266"}
    ],
    "src":"https://s3.amazonaws.com/grassrootsmapping/warpables/306187/DJI_1207.JPG",
    }
  ]
}
```

Do you want avg_cm_per_px and scale incorporated like this:
```
{
  'images': [
    {
    "cm_per_pixel": 4.99408,
    "nodes": [ 
      {"lat":"-37.7664063648","lon":"144.9828654528"}, // id is also optional here
      {"lat":"-37.7650239004","lon":"144.9831980467"},
      {"lat":"-37.7652020107","lon":"144.9844533205"},
      {"lat":"-37.7665844718","lon":"144.9841207266"}
    ],
    "src":"https://s3.amazonaws.com/grassrootsmapping/warpables/306187/DJI_1207.JPG",
    }
  ],
  'avg_cm_per_px': x,
  'scale': x
}
```

**Comment by jywarren** [comment]
This is great! OK, so shall we merge this and move on to a function that can submit this to https://exports.mapknitter.org and parse and display the results? 

I think this initial version could just periodically fetch from the returned address for `status.json` and then `console.log` the contents of the `status.json` every X interval?  What do you think?

**Comment by jywarren** [comment]
This fetcher could be called `distortableCollection.startExport(callbackFn)` and accept a function like:

```
function callback(response) {
  console.log(response)
}
```

**Comment by jywarren** [comment]
Then in future versions we could use that callback to update a progress bar!

**Comment by jywarren** [comment]
This is so exciting!!!!!!

**Comment by sashadev-sky** [comment]
@jywarren it still doesn't have "avg_cm_per_px" and "scale" incorporated. Do I still need to incorporate this? (see the question in the 2nd half of my comment)

**Comment by jywarren** [comment]
Actually i think `avg_cm_per_pixel` and `scale` are the same info - although i think one is the inverse of the other... In any case, yes, but why don't we address it in another PR, which will provide `distortableCollection.avg_cm_per_pixel` and then we can have `generateExportJson` pull from that. I think we should merge this and make a checklist of follow-ups:

* [ ] `distortableCollection.avg_cm_per_pixel`
* [ ] `generateExportJson` pulls from `distortableCollection.avg_cm_per_pixel`
* [ ] `distortableCollection.startExport(callbackFn)` with basic `console.log` callback function to show progress every X seconds

**Comment by sashadev-sky** [comment]
@jywarren sounds good! I just opened issue #270 with the checklist

**Comment by jywarren** [comment]
Awesome!!! Great, Sasha!

**Pull request merged**
