### PR TITLE
Appending Image using getPane() method

### LINKED ISSUE #354: Use leaflet `.getPane()`
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/Leaflet.DistortableImage/issues) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

**What's supposed to happen:**

Where we can, it is best to use methods from the Leaflet API instead of working directly with the underlying private variables they update.

**What actually does happen:**

In our `L.DistortableImageOverlay` class, we grab the overlay's pane on the map and append an image to it:

https://github.com/publiclab/Leaflet.DistortableImage/blob/a83f9868b8dd482d4edfebf069de814dce1e8adb/src/DistortableImageOverlay.js#L29

Let's update this to use Leaflet's [`getPane()`](https://leafletjs.com/reference-1.5.0.html#layer-getpane) method, which does the same job.

## Solution

Update the above line to:

```JS
this.getPane().appendChild(this._image);
```

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/Leaflet.DistortableImage](https://github.com/publiclab/Leaflet.DistortableImage)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, if there's an additional checklist provided for getting it merged, get those boxes checked off. Either way, mention me @sashadev-sky for a review.

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

### PR DESCRIPTION
**Pull request by gowtham5699**
Fixes #354  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [ ] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by gowtham5699** [comment]
@sashadev-sky Please review this.

**Comment by sashadev-sky** [comment]
@gowtham5699 Sorry for the delay! need to undo the last pull request because this is not what was meant to happen:
```JS
$ git reflog
// Find the action where you add your first commit here HEAD@{#}
$ git reset --hard HEAD@{#} - paste the HEAD there
```

Then make sure you have done `$ npm install` already. and run `$ grunt`. This should say grunt is watching files and compiling or something along those lines, and should update your dist file. Do `$ git status` and you should find your dist file has changes and can be committed. 

If running `$ grunt` for some reason does not update the file, try `$ grunt concat:dist` and check the status again afterwards.

Only add this file, not package-lock.json: `$ git add dist/leaflet.distortableimage.js`, commit and then force push (bc you did a reset earlier): `$ git push -f origin getPane/method`

Let me know how this goes!

**Comment by gowtham5699** [comment]
Upadated dist file. There is some issue with grunt. So, as you said i ran $grunt concat:dist and it got updated. Thank you for the help.

**Comment by gowtham5699** [comment]
`fff`

**Comment by sashadev-sky** [comment]
@gowtham5699 no problem! I think you may have forgotten to add the update `dist` file and commit it!

**Comment by gowtham5699** [comment]
@sashadev-sky Sorry about that..Done.

**Pull request merged**
