### PR TITLE
fixed downloadJSON error

### LINKED ISSUE #1352: downloadJSON error in JS
https://github.com/publiclab/Leaflet.DistortableImage/blame/e451976953ba3d5f810b333be5e5eeaa67c4c27b/examples/js/archive.js#L348

I got an error that downloadJSON was not defined, and I think that variable name was just changed by @7malikk -- can you check this and look for a fix? I wonder if you forgot to check in a corresponding change elsewhere? Thanks!

### PR DESCRIPTION
**Pull request by 7malikk**
Fixes #1352 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [x] code is in a uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updates
* [x] @mention the original creator of the issue in a comment below for help or for a review

### UI Changes
downloadJSON-three

### CODE REVIEW

**Comment by 7malikk** [comment]
@jywarren All done here, thanks!

**Comment by 7malikk** [comment]
@jywarren Ready for merge

**Comment by jywarren** [comment]
It's so strange... I don't actually see the change in https://github.com/publiclab/Leaflet.DistortableImage/pull/1354/files, but, in this screenshot, it shows that it's already been fixed??

image

Ah, i see - @7malikk did you commit to the main branch separately? 

https://github.com/publiclab/Leaflet.DistortableImage/commit/d4c5d123fac4039570726296a3407dffeb7af44c

If so, it's OK in this one situation because it's a fix but I'd like to coordinate all commits together and do them through PRs. Maybe somehow you accidentally pushed to PublicLab's main branch?

**Comment by jywarren** [comment]
In any case, it looks like we are OK now, I can merge this to include your final tweaks... but yeah, I think maybe somehow you were unintentionally pushing to PublicLab's main branch?

**Comment by 7malikk** [comment]
Oh maybe I did, unintentionally. But that's so weird

**Comment by jywarren** [comment]
Hmm, what I'll do is put some more branch protection on so you can't do it unintentionally. No worries!

**Comment by 7malikk** [comment]
Alright, thanks @jywarren

**Pull request merged**
