### PR TITLE
feat: 🎸 create images sidebar

### LINKED ISSUE #1018: Have a sidebar for displaying the images in a collection

### PR DESCRIPTION
**Pull request by PeculiarE**
Fixes #1018

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updates
* [x] @mention the original creator of the issue in a comment below for help or for a review

### CODE REVIEW

**Comment by PeculiarE** [comment]
Hi @jywarren! So here's a demo of how the sidebar looks. I tried to also make it as mobile responsive as possible. What do you think? Is the design and flow okay? 


https://user-images.githubusercontent.com/75625011/188762892-65a3f6f0-5a68-4907-afda-80aeefda479e.mp4

**Comment by PeculiarE** [comment]
And I took your advice: for now, we are simply verifying that we are receiving the URL inputted by the user.

The next step in the process would then be to retrieve the images from the received URL.

**Comment by jywarren** [comment]
Wow this is wonderful Peculiar! Really nice! Is it ready to merge? I can do so right away if so.

**Review by jywarren — APPROVED** [review]

**Comment by PeculiarE** [comment]
Thank you ❤️, Jeff! And yes, this can be merged.

**Comment by jywarren** [comment]
Ok super! And good luck with the next one, it should be fun to see!

**Pull request merged**
