### PR TITLE
Deletion bug fix

### PR DESCRIPTION
**Pull request by sashadev-sky**
Fixes #https://github.com/publiclab/Leaflet.DistortableImage/issues/186#issuecomment-487110755 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updates
* [x] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sashadev-sky** [comment]
bugfix

@rexagod fixed the bug you found!

**Comment by sashadev-sky** [comment]
@jywarren for some reason the dist file in the main repo isn't updated to reflect the changes I merged recently from FTOs. But it updates it here, so there are a few extra updates in the dist file

**Comment by sashadev-sky** [comment]
This is a small change and i didn't get any feedback on it for a week so i just merged it

**Comment by jywarren** [comment]
It's been busy, apologies! I'm hoping that now that SoC has started officially, @rexagod can offer a bit more reviewing -- but perhaps we should brainstorm who else can offer reviews too, since it's going to be a busy summer! Thank you for taking action 👍

**Comment by sashadev-sky** [comment]
@jywarren sorry that was not good practice to merge. I don't know anyone is capable of reviewing front end code really. The FTOs haven't been sticking really but perhaps thats because we haven't implemented any strong system for follow up like in plots2. (create a page here with incentives for following the workflow through on this repo and a reviewers team, add FTO badges etc.) This repo has a simple setup so low barriers to entry and could benefit a lot from community coordination like @gauravano has been doing. I can do some extra work to try to make it gain traction. We can discuss further when we go over everything and other alternatives!

**Comment by jywarren** [comment]
That's ok and I hear you on wanting to shore up the contributor community
to get good feedback. Actually in image-sequencer there was an attempt to
use a service to auto generate an online demo for any PR, which could help
with front end reviews. I think it was called Surge.

**Comment by gauravano** [comment]
I found this - https://medium.com/onfido-tech/travis-surge-github-auto-deploy-every-pr-branch-and-tag-a6c8c790831f :smile:. It would be exciting to try. 

Also, can feel you @sashadev-sky that it can be frustrating too sometimes to wait for approval on small things. But, you are really doing great work :raised_hands:  and we'll surely get more hands once we get these projects to stability. I think, our next goal towards coordination should be to use automation/tools at their best and also to develop a strategy which attracts more contributors and preparing more people to step-up as reviewers/maintainers.

**Comment by jywarren** [comment]
I think I'm going to ask SoC folks also to start to build on their initial work to begin thinking about and incorporating community building and reviewing as part of their summer projects. We are still figuring out how to not work in separate siloes. Thanks Gaurav I totally agree! 💓🔥🙌🏽

**Comment by sashadev-sky** [comment]
@jywarren @gauravano that sounds really cool will definitely check out surge! Yeah that's tough to figure out - you don't want people submitting approval reviews just for the sake of it. But the Mapknitter Rails upgrade project has been an awesome example of collaboration. I guess the trick is having simultaneous related projects. Next after that is asking someone directly for help

**Pull request merged**
