### PR TITLE
add rotate and scale actions

### LINKED ISSUE #208: icons for Rotate and Scale for custom toolbars
It currently does not. If not, why?

@jywarren @rexagod 

==========
**UPDATE** - have decided that we will make icons for these so that a user can add them to the toolbar if they would like, but they will not be default actions in it. So before this, must first implement **custom toolbars**

### PR DESCRIPTION
**Pull request by sashadev-sky**
Fixes #208 (<=== Add issue number here)
- #353 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [ ] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

changes:
- this pr allows the user to specify `Rotate` and `Scale` actions now in the actions array - they are not just only a keybinding now. But they are still not included in the default actions array.
image

- **Bug Fix**:in my pr #353 I removed `showToolbar` called after every action, but I have realized that now the action icons don't update on keypress, just icon click. This fixes that bug.

- I removed the `EnableEXIF` function as a default action until we get it working via #169

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@rexagod can I get a review here please :) See pr description for details. I updated the `index.html` file so if you pull it you can easily see the new additions im showing.

**Comment by jywarren** [comment]
Yay, thanks and great work!

**Comment by jywarren** [comment]
Shall we add this as an example to the README too?

**Comment by sashadev-sky** [comment]
@jywarren It is already in README that you can add them as extra actions!

**Comment by sashadev-sky** [comment]
@jywarren note that this PR restored the toolbar icon toggle on hotkey functionality, so we'll want to bump version # and connect to MK

**Pull request merged**
