### PR TITLE
fix max zoom

### LINKED ISSUE #473: Increase max zoom to 24
We can no longer zoom in very close; it used to allow up to zoom 24, but we're now limited to much lower (18?) -- but here is a post about the high-res we used to have:

https://publiclab.org/notes/warren/01-19-2018/mapknitter-update-very-high-resolution-mapping (It was added in this PR: https://github.com/publiclab/mapknitter/pull/243/files#diff-cd467f0b470669270454ce0ae6227a90R492-R493)

I think this was changed when [GoogleMutant was moved into the Leaflet.DistortableImage library](https://github.com/publiclab/mapknitter/pull/959/files#diff-cd467f0b470669270454ce0ae6227a90R615)! 

But the fix is pretty simple! Just these lines:

https://github.com/publiclab/Leaflet.DistortableImage/blob/6e4b078eb83ddefa191a726be8a2671640897cba/src/mapmixins/MapMixins.js#L11-L12

Have to be changed to match these (see docs at https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant):

```js
    var googleMutant = L.gridLayer.googleMutant({
      type: 'satellite', // valid values are 'roadmap', 'satellite', 'terrain' and 'hybrid'
      maxZoom: 24,
      maxNativeZoom: 20,
      opacity:0.5
    }).addTo(this._map);
```

We'd love help with this and it would be a great GCI task! cc @sashadev-sky

### PR DESCRIPTION
**Pull request by jywarren**
Fixes #473

Back to 24! :tada:

image

### CODE REVIEW

**Comment by jywarren** [comment]
Can we add a test using `map.getMaxZoom()`?

**Comment by sashadev-sky** [comment]
chhecking it put now

**Comment by sashadev-sky** [comment]
@jywarren I added in the `maxNativeZoom` option for the labels too, or else if you double click to access the labels at a high zoom you'll throw an error.

**Is there a reason we want this map to be able to go all the way up to 24?** At 24 it really doesn't look like anything to me.

Here is the same view on the map at various zooms:

24:
image

vs, to me, 22 seems to be the highest acceptable zoom:
image

20 is the 1st to look good quality:
image

So seems like maybe 21 would be a good option to meet in the middle?

**Comment by sashadev-sky** [comment]
Also sorry I commited some formatting change for `src/edit/handles/DragHandle.js` here. It was converted to LF and being really stubborn so I just linted it and pushed. hope thats ok!

**Comment by jywarren** [comment]
Yes, because a significant amount of aerial photography uploaded as distorable image overlays are so far above the background resolution that they require 24 zoom (or higher!) to properly rectify against each other. That's how much better mapknitter maps are than Google maps! 🎉💥 

Especially folks doing pole photography :-)

https://PublicLab.org/tag/pole-photography

**Comment by jywarren** [comment]
Can we assert getMaxZoom in this file?

https://github.com/jywarren/Leaflet.DistortableImage/blob/maxZoom24/test/src/DistortableImageOverlaySpec.js

**Comment by sashadev-sky** [comment]
@jywarren sure I will a final look at this and write some tests. Might be a bit of delay because work but not a long one.

**Comment by jywarren** [comment]
I added a simple test, although I'm not sure if wrapping the `expect()` with `map.whenReady(function() {` will make it fail silently if the `whenReady` doesn't complete before the test moves on to the next assertion? 

If it is an issue, could we hold it open by passing a "done()" callback into the test, and running it only when the `whenReady` is completed?

**Comment by jywarren** [comment]
OK I made that change, and we should be good now!

**Pull request merged**
