### PR TITLE
Update config.yml #1072

### PR DESCRIPTION
**Pull request by NPDebs**
This PR fixes issue #1072 
The file has been edited as requested.

config yml #1072

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updates
* [x] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by NPDebs** [comment]
Hi @TildaDares. 
Here is a PR for the issue you assigned me. Please, kindly review it. Thank you!

**Review by TildaDares — APPROVED** [review]
Amazing work @NPDebs. Thank you!!

**Comment by TildaDares** [comment]
Congratulations on merging your PR @NPDebs 🎉🎉

**Comment by NPDebs** [comment]
> Congratulations on merging your PR @NPDebs 🎉🎉

Thank you. 😭😭🤍🤍

**Comment by NPDebs** [comment]
> Congratulations on merging your PR @NPDebs 🎉🎉

I'm ready to take on more issues, please! 🙌🏼

**Comment by TildaDares** [comment]
Hi @NPDebs, we always encourage contributors to create FTOs for others or look out for issues with the `bug /help wanted` tags.

If you'd like to create an FTO for someone else, you can look through the repo or [publiclab.org](https://publiclab.org/) for issues that can be solved in a few lines. When you've found an issue for a first-timer to work on, click the New Issue button and use the issue template named First Timers Only issue.

Thank you!

**Comment by NPDebs** [comment]
> Hi @NPDebs, we always encourage contributors to create FTOs for others or look out for issues with the `bug /help wanted` tags.
> 
> If you'd like to create an FTO for someone else, you can look through the repo or [publiclab.org](https://publiclab.org/) for issues that can be solved in a few lines. When you've found an issue for a first-timer to work on, click the New Issue button and use the issue template named First Timers Only issue.
> 
> Thank you!

Contribute and help others contribute. 🤝🏻🚀
Duly noted. I'll keep my eyes wide open. 🧐

Thanks again. 👍🏻

**Pull request merged**
