### PR TITLE
Toggle locks

### LINKED ISSUE #321: Make locked images selectable
This is important because for multiple image select, many images may be locked even as you're looking to export them. Let's make this change, and think through next steps:

If the lock icons still show, we should be OK, although perhaps we want to make groups unlockable. 

But if the lock handle icons (`X`s) /don't/ show, we may need to add that (not in the initial fix but in follow-up) so that it's clear why you can't drag the images together. That should resolve any ambiguities!

### PR DESCRIPTION
**Pull request by sashadev-sky**
Fixes #321  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updates
* [x] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

changes
- [x] `_removeFromGroup` renamed `_removeGroup` for consistency and clarity.

=============
pending 
- [x] allow lock mutli-images to be selected with command mousedown
- [x] after group locking, image dragging is disabled
- [ ] handle keybindings
- [x] this is going to need some tests eventually for future developers
  - test:
     - after group looking, image dragging is disabled
     - locks all selected images
     - unlocks all selected images
=============

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@jywarren if this is still priority, this is ready! I was going to write a few tests for it and document but can follow up on that in a new PR
Below shows:
- 1. Images can be multi-selected when locked
- 2. Locked images wont be dragged still
- 3. You can unlock and lock a group
- 4. Changing the lock state from the control bar also updates the icon for the individual bar
multiLock2

**Comment by sashadev-sky** [comment]
You still cannot `delete` locked images
multiLock3

**Comment by sashadev-sky** [comment]
I confirmed that locked images are counted in the array of `json.images` to export.

**Comment by sashadev-sky** [comment]
@jywarren actually wait one more important thing to address. So it did not make sense to make a `toggleLock` for the group because that would be confusing with a group with various lock states.
So there is a `Locks` and `Unlocks` action with keybindings `l` and `u`, respectively.

I am thinking for consistency we should update the keybindings for the individual image to match, and separate out `toggleLock` into `Lock` and `Unlock` (they would still share one icon though). What do you think?

**Comment by sashadev-sky** [comment]
@jywarren also I renamed `_removeFromGroup` to `_removeGroup` for consistency and clarity (its just a private method for the `Deletes` action. Thankfully that ones not in MK so it wont mess with anything there!

**Comment by jywarren** [comment]
Amazing! Bumped to 0.6.0 and will merge and release asap. Enjoy the holiday!

**Comment by sashadev-sky** [comment]
Thank you!! You too! 

I had a question here still: https://github.com/publiclab/Leaflet.DistortableImage/pull/324#issuecomment-508307167
but we can go over it after the holiday

**Pull request merged**
