### PR TITLE
feat: 🎸 display collection's images in sidebar

### LINKED ISSUE #1013: Fetch and display all the collection's images in the sidebar
On inputting a valid Internet Archive URL, the images saved in that collection should be displayed on the sidebar.

### PR DESCRIPTION
**Pull request by PeculiarE**
Fixes #1013

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updates
* [x] @mention the original creator of the issue in a comment below for help or for a review

### CODE REVIEW

**Comment by PeculiarE** [comment]
**Demo 1: Different responses to different inputs**

https://user-images.githubusercontent.com/75625011/191161886-7058581d-87b3-45b3-8002-dce28324445d.mp4

**Comment by PeculiarE** [comment]
**Demo 2: More IA URLs:**

https://user-images.githubusercontent.com/75625011/191161914-2b26a7ce-1dab-4ca9-aaa1-4cf0d87b5284.mp4

**Comment by PeculiarE** [comment]
**Demo 3: No image in the collection**

https://user-images.githubusercontent.com/75625011/191161947-b76e424c-7980-4ae6-add3-b8bc224f5723.mp4

**Review by jywarren — APPROVED** [review]
Really good work Peculiar!!! Thank you!!

**Pull request merged**
