### PR TITLE
added _calculateAngle to L.EditHandle

### LINKED ISSUE #260: Refactor out `_calculateAngle` method
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/Leaflet.DistortableImage/issues) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

We rewrite the same function, `_calculateAngle` in a few of our files for each new "handle" class to have. Instead, we can define this function on `L.EditHandle`, the common class the other handle classes extend, and it will be available to all of them.

## Solution

**Where to find the relevant lines of code**: 

Delete  the `_calculateAngle` function from the following files:

1) 
https://github.com/publiclab/Leaflet.DistortableImage/blob/d91b2d7e946ae8ce064535dea8a0320683934b1f/src/edit/RotateHandle.js#L28-L40

2) 
https://github.com/publiclab/Leaflet.DistortableImage/blob/d91b2d7e946ae8ce064535dea8a0320683934b1f/src/edit/RotateScaleHandle.js#L44-L56

3) 
https://github.com/publiclab/Leaflet.DistortableImage/blob/d91b2d7e946ae8ce064535dea8a0320683934b1f/src/edit/ScaleHandle.js#L29-L41

4) Then, copy it into `src/edit/EditHandle.js` (you can add it as the last function defined on the `L.EditHandle` class).

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/Leaflet.DistortableImage](https://github.com/publiclab/Leaflet.DistortableImage)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, if there's an additional checklist provided for getting it merged, get those boxes checked off. Either way, mention me @sashadev-sky for a review.

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

### PR DESCRIPTION
**Pull request by AdityaShD**
Fixes (#260 )

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updates
* [x] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by AdityaShD** [comment]
@sashadev-sky please review this pull request once and let me know if i need to change something. Thanks:)

**Comment by sashadev-sky** [comment]
@AdityaShD This is really great work, thank you!! 😊 I'm going to rebase it for you because I just merged another PR updating these files.

Then I will merge it!

**Comment by sashadev-sky** [comment]
Oh @AdityaShD one quick tip - I just realized this myself:

don't put parentheses around the issue # when you write fixes #260 . The exact syntax given in the template (without the parentheses) triggers the connected issue to automatically close when its corresponding PR is merged.

**Comment by AdityaShD** [comment]
hi!!!
My twitter handle is @_aditya_sh_ <https://twitter.com/_aditya_sh_>

**Comment by AdityaShD** [comment]
> Oh @AdityaShD one quick tip for future PRs - I just realized this myself:
> 
> don't put parentheses around the issue # when you write fixes #260 . The exact syntax given in the template (without the parentheses) triggers the connected issue to automatically close when its corresponding PR is merged.

sure, i'll keep it mind next time   :blush:

**Comment by AdityaShD** [comment]
> Congrats on merging your first pull request! 
> Your code will likely be published to https://mapknitter.org in the next few days.
> In the meantime, can you tell us your Twitter handle so we can thank you properly?
> Now that you've completed this, you can help someone else take their first step!
> See: [Public Lab's coding community!](https://code.publiclab.org)

My twitter handle is @_aditya_sh_ 
Thanks  :smile:

**Comment by AdityaShD** [comment]
Check out this awesome course I am doing on CodingNinjas.com

CodingNinjas_logo ( https://u3048307.ct.sendgrid.net/ls/click?upn=HWQn5awVFF-2FZNbrxzhMVBRc408qtyBQqVSF9b1EAd4SWEO-2BSjSzRFf3hEH7UbLxas-2BcWpRI-2BNknFq40SOJ5TAQ4tD0-2Bn6pTMutPaQ0D3Tk1-2BTyu0kXruhu341u96mrNnva4KeqYES0X4iLnegnJF9A-3D-3D7snC_U31jt5HgHBh7k3Grc5s4l5ik1K90VM-2Br6u7lMqac7arFd5U63JbRXOW-2FFksyn-2BbAFQYm465VyFjJUImvVjTtHAPIdWqa8hZQner6OJEzF0Aly5auUWJlUHwzH9ACDQCEQLWghMcbD-2B9RHgXsFbAYXkQpFMZlsRNNKqHVn1-2F4F4edoHd6hcqsRdHYZL4pBJ6rHkiCZXYBzviil4muU9TtIGdzVOKCcZr2jETCo6-2Bdz9J3G9PnzJhgpAv-2FEYTv9q1qV8CDUGnRvpuAG4Oc-2BDzW7jW6a922IWK9EY-2Bqy6qzYo1UOU3g9Gn5pHcFVRNim-2F-2FezJP-2FWQkDp3rQDYkdf4oUWS19l2WhpCsbh6p8PJdpuRkZbBWuOxzK8wgNxG4kBPaUTNU5x9oVOHyiVd01TonYtbpjCte-2BMxnSHhErnCqxCIAmIa3p4IDKD8iYvQ1DaEHsfUsUAy54pMbyp02Z82Qhpg-3D-3D )

Hey !

I have been learning Web Development with Ruby on Rails with *Coding Ninjas.* The learning  experience has been amazing and I would encourage you to check it out as well.

As a current student, I can extend *a discount of* *Rs 1000* to my friends. You can avail that by clicking the link below.

Claim Rs 1000 Discount ( https://u3048307.ct.sendgrid.net/ls/click?upn=HWQn5awVFF-2FZNbrxzhMVBRRoDigMZIUh14ShH1YL-2FpkF9yKkjq6ffkw1KYwbppBcOAtTocG1739xyBr9FHPrdZdAtrC79CGv92QPgz1rDqqkJFGqlAuWS34yCWY90MH0FKi1S9uTYS3-2BJuh3zt32gF8I-2FhKXBnpFceWPpc-2B0u5vF3tSDXL0DdirpJ8m-2Fwk1ECuOK_U31jt5HgHBh7k3Grc5s4l5ik1K90VM-2Br6u7lMqac7arFd5U63JbRXOW-2FFksyn-2BbAFQYm465VyFjJUImvVjTtHAPIdWqa8hZQner6OJEzF0Aly5auUWJlUHwzH9ACDQCEQLWghMcbD-2B9RHgXsFbAYXkQpFMZlsRNNKqHVn1-2F4F4edoHd6hcqsRdHYZL4pBJ6rHkiCZXYBzviil4muU9TtIGdzVOKCcZr2jETCo6-2Bdz9J3G9PnzJhgpAv-2FEYTv9q1qV8CDUGnRvpuAG4Oc-2BDzW7mmfrpkJ89EZGUp0Rt5BJbJQofawkHn9K7ekdsjInNUbw9bco1ZEXIJ9fMLzXb7I2-2BrndLz28nzgp3riDuYEHzUyB1efohBvgfG41VviHZRoJETCNqXnPYK2AyL7s2MGW3OIf6uOaJvbVg9gQ-2B88d9CFQBkLGNAMZxt3Uspl8aUtrfkoegKIHVsDEszqyrh0RA-3D-3D )

Happy Learning, looking forward to learn together!

Best,
Aditya Sharma

CodingNinjas_logo ( https://u3048307.ct.sendgrid.net/ls/click?upn=HWQn5awVFF-2FZNbrxzhMVBRc408qtyBQqVSF9b1EAd4SWEO-2BSjSzRFf3hEH7UbLxas-2BcWpRI-2BNknFq40SOJ5TAQ4tD0-2Bn6pTMutPaQ0D3Tk1-2BTyu0kXruhu341u96mrNnva4KeqYES0X4iLnegnJF9A-3D-3D3KxN_U31jt5HgHBh7k3Grc5s4l5ik1K90VM-2Br6u7lMqac7arFd5U63JbRXOW-2FFksyn-2BbAFQYm465VyFjJUImvVjTtHAPIdWqa8hZQner6OJEzF0Aly5auUWJlUHwzH9ACDQCEQLWghMcbD-2B9RHgXsFbAYXkQpFMZlsRNNKqHVn1-2F4F4edoHd6hcqsRdHYZL4pBJ6rHkiCZXYBzviil4muU9TtIGdzVOKCcZr2jETCo6-2Bdz9J3G9PnzJhgpAv-2FEYTv9q1qV8CDUGnRvpuAG4Oc-2BDzW7lYbGV9SKHq-2BhOwDLlpfAajA2kNtt-2F9oIekcT9SJ4eESo4mVzS9MuqZwbGapik45-2FfYcz8SJ5qJ6Rozk8USf8FB3UQg4fZ-2F93b86Zol3UHkk5VHGSTV4VBNCi0XXD8ZRTMOYvtY-2B8VEj5I55AvSKcBIcLULeOmf56y3nhmtfd3G0p89kv-2BZrhS1KTxxVbAv5aw-3D-3D )

Unsubscribe (  <%asm_group_unsubscribe_raw_url%>  ) - Unsubscribe Preferences (  <%asm_preferences_raw_url%>  )
If you would like to unsubscribe and stop receiving these emails click here: https://u3048307.ct.sendgrid.net/wf/unsubscribe?upn=s5UH8bhnBaopYjthcNSRcaeE-2Fv3C9WbU0sSrS93A9gdGlx2nBRsgRlgtCA3s-2FrEYQWXT-2Fe5hbsEfjAcnFTBYnu70tLKlshl0jthShoe4bAWJTHpi-2FWR7jWOplLnVE8p-2F-2BwQXL2RrHw7tYi8EKBmS6j9jndL6G6GjlHoU2ngnMTKfwCWcbebCFLLImdY1CPwddzXES3K3SfPuSsUBRS5iP3Atx36ABwTchCw9FjYn-2FNIkhRi8J1iHIN9p86kiRAQojZPBEnA2kMN6t0Aw2E-2BIShy1HCmTZnjICFQLk4-2F6-2FwWYEwSc5EUA99SpzXe74sAMVwduFVDCWIzN3-2Bxz0Y-2Bvs7k1MHHPGlpSFqqYIYJX2OGqPry-2BQrLG2TdwfBRu0kD7Xq3pbgCmrSelkA5-2FVozc9-2F4-2FHSPFAYZLQqSbFbEUq5XRY-2F-2F64HE0yuW8cCrgpktfJ1PeUCSZ9Suxr9mBUbpuvQ-3D-3D.

**Pull request merged**
