### PR TITLE
Add lang attribute to the html element#1133

### LINKED ISSUE #1133: Add `lang` attribute to the `html` element
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from underrepresented groups in free and open-source software!

We know that the process of creating a pull request is one of the biggest barriers for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Claim the issue by commenting. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

<details>
  <summary>💡 <i>Learn how to claim</i> 🙋</summary>
  <h3>Claiming an issue</h3>
  <p>Unless the issue is marked as reserved for someone, you can just say "I'd like to try this!" and then you've claimed it - no need to wait for someone to assign it to you. Just be sure you link your pull request (PR) to this issue so we can see where your solution is.</p>
  <p>And open one early if possible - even before you've completed it with additional commits - and others can help you figure out any issues you may face.</p>
</details>

- [ ] 📝 **Update** the file [index.html](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/index.html) in the `Leaflet.DistortableImage` repository (press the little pen Icon) and edit the line as shown below.

```diff
-2 <html>
+2 <html lang="en">

```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by Straw4yu**
Fixes #1133  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [*] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [*] code is in uniquely-named feature branch and has no merge conflicts 📁
* [*] screenshots/GIFs are attached 📎 in case of UI updates
* [*] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by Straw4yu** [comment]
I think it's great

**Comment by leilayesufu** [comment]
Hii, @Straw4yu 
I do think your pr looks good but the - and + sign was to indicate to line to be removed and added so it’s not meant to be in the code, kindly make that correction then tag @TildaDares for a review

**Comment by leilayesufu** [comment]
Hii, @Straw4yu 
This looks great to me, let’s wait for @TildaDares to give the final review

**Review by TildaDares — APPROVED** [review]
Amazing work @Straw4yu. Thank you!

**Comment by TildaDares** [comment]
Thanks for the reviews @leilayesufu!!

**Comment by TildaDares** [comment]
Congratulations on merging your PR @Straw4yu 🎉🎉

**Comment by leilayesufu** [comment]
Anytime!! @TildaDares 
Can I close the issue now?

**Comment by TildaDares** [comment]
Yes you can @leilayesufu. Thank you!

**Pull request merged**
