### PR TITLE
Updating DoubleClickZoom method creation syntax for ES6

### LINKED ISSUE #632: Update L.Map.DoubleClickZoom.js method creation to ES6 syntax
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/Leaflet.DistortableImage/issues) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

We just added support for ES6 in our library, and would like to start transitioning our code to use this syntax.

Let's update the method creation syntax in the `src/mapmixins/DoubleClickZoom.js` file from ES5 to ES6.

## Solution

For the 6 `L.Map.DoubleClickZoom` methods, remove the `function` keyword and attach the method arguments to the method name instead.

Here is an example of how this will look for a different method. These ones should follow suit:

ES5
```JS
radiansToDegrees: function(angle) {
  return (angle * 180) / Math.PI;
},
```

ES6
```JS
radiansToDegrees(angle) {
  return (angle * 180) / Math.PI;
},
```

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/Leaflet.DistortableImage](https://github.com/publiclab/Leaflet.DistortableImage)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, if there's an additional checklist provided for getting it merged, get those boxes checked off. Either way, mention me @sashadev-sky for a review.

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

### PR DESCRIPTION
**Pull request by calvincodes**
Fixes #632 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [x] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by calvincodes** [comment]
Running `grunt test` on local passes all the test cases. I think the above CI failure might be related to this.

**Local `grunt test` output:**
```
➜  Leaflet.DistortableImage git:(updating-l.map.doubleclickzoon.js-method-creation-to-es6-syntax) grunt test
Running "jshint:source" (jshint) task
>> 44 files lint free.

Running "jshint:grunt" (jshint) task
>> 1 file lint free.

Running "karma:test" (karma) task

START:
25 04 2020 18:56:34.488:INFO [karma-server]: Karma v5.0.2 server started at http://0.0.0.0:9876/
25 04 2020 18:56:34.489:INFO [launcher]: Launching browsers PhantomJS with concurrency unlimited
25 04 2020 18:56:34.499:INFO [launcher]: Starting browser PhantomJS
25 04 2020 18:56:35.419:INFO [PhantomJS 2.1.1 (Mac OS 0.0.0)]: Connected on socket Drfdr9VxEhAsOz_NAAAA with id 43890464
  L.DistortableCollection
    ✖ Should keep selected images in sync with eachother during translation (skipped)
    ✔ Adds the layers to the map when they are added to the group
    #isCollected
      ✔ Should only return true if the image was selected using shift + mousedown
    #anyCollected
      ✔ Should return false if no selections were made with shift + mousedown
    #_toggleCollected
      ✔ Should allow multiple image selection (collection) on shift + click
      ✔ It should allow a locked image to be part of multiple image selection
  L.DistortableImageOverlay
    initialization
      ✔ should add Google tile base layer via Google Mutant library, with maxZoom of 24
    initialization: actions option
      ✔ The image will be initialized with a default set of actions if not passed
      ✔ Will initialize the image with the passed array of actions
      ✔ Will initialize an image with no actions if passed an empty array
    initialization: mode option
      ✔ Will initialize the image with the passed mode, if available
      ✔ A mode is unavailable if it either does not exist or is restricted via the `actions` option
      ✔ If the mode is unavailable, the image's mode will be the 1st available one
      ✔ If not passed, the image will have the default mode, `distort` if available
    #_calculateProjectiveTransform
      ✖ Should (skipped)
    #select
      ✔ Allows programmatically selecting a single image
      ✔ Is also invoked on image click
      ✔ Locked images can be selected
      ✔ Returns undefined if image editing is disabled
      ✔ Returns undefined if the multiple image editing interface is on
    #deselect
      ✔ Allows programmatically deselecting a single image
      ✔ Is invoked on map click
      ✔ Returns undefined if image editing is disabled
    #isSelected
      ✔ Only returns true for a selected image
    #getCenter
      ✔ Should return the center when the outline of the image is a rectangle
    #scaleBy
      ✔ Should not change image dimensions when passed a value of 1 or 0
      ✔ Should invert image dimensions when passed a negative value
      ✔ Maintains image proportions when scaling
    #rotateBy
      ✔ Should not rotate the image when passed a value of 0 or 360
      ✔ Should rotate the image by the specified units, otherwise by degrees
      ✔ Rotates the image counter clockwise for negative values
      ✔ Rotates the image by the remainder for values higher than the degrees in a circle
    #getAngle
      ✔ Returns the image's rotation angle in the specified units, otherwise in degrees
      ✔ Returns the correct angle even when the image is flipped
      ✔ Always returns a number greater than or equal to 0
    #setAngle
      ✔ Sets the image's rotation angle in the specified units, otherwise in degrees
      ✔ Sets the image's rotation angle to the remainder for values higher than the degrees in a circle
      ✔ Subtracts negative values from the total degrees in a circle
      ✔ Sets the correct angle even when the image is flipped
  L.DistortableCollection.Edit
    #_decollectAll
      ✔ Should remove the 'selected' class from all images
      ✔ Should hide all images' handles unless they're lock handles
      ✔ Should remove an image's individual toolbar instances regardless of lock handles
    #_addToolbar
      ✔ is invoked on the click event that follows mousedown multi-select
      ✔ it adds a control toolbar to the map
      ✔ does not add multiple instances of a control toolbar
    #_removeToolbar
      ✔ is invoked on map click
      ✔ is invoked on shift + mousedown when it toggles the image *out* of multi-select
      ✔ it removes a control toolbar from the map
      ✔ it returns false if there was no control toolbar to remove
    #_lockGroup
      ✔ it only puts the multi-selected images in lock mode
      ✔ does not toggle lock mode
      ✔ prevents images in that group from being dragged
    #_unlockGroup
      ✔ it removes the multi-selected images from lock mode
      ✔ does not toggle lock mode
CONFIRM: '2 Are you sure? These images will be permanently deleted from the map.'
    #_removeGroup
      ✔ removes a collection of layers
CONFIRM: '2 Are you sure? These images will be permanently deleted from the map.'
      ✔ removes the layers from the map on removal from group
  L.DistortableImage.Edit
    ✔ Should be initialized along with each instance of L.DistortableImageOverlay.
    ✔ Should keep handles on the map in sync with the corners of the image.
    #replaceTool
      ✔ It should replace an existing action
      ✔ It should do nothing if the first parameter does not exist
      ✔ It should do nothing if the second parameter already exists
      ✔ Should add the new action to the image's `modes` if it is also a mode
    #_deselect
      ✔ It should hide an unlocked image's handles by updating their opacity
      ✔ But it should not hide a locked image's handles
      ✔ Should remove an image's individual toolbar instance regardless of lock handles
    #nextMode
      ✔ Should update image's mode to the next in its modes array
      ✔ Will also select the image when triggerd by dblclick
      ✔ It prevents dblclick events from propagating to the map
      ✔ Should call #setMode
      ✔ Will still update the mode of an initialized image with suppressToolbar: true
    #setMode
      ✔ Will return undefined if the passed value is not in the image's modes array
      ✔ Will return undefined if image editing is not enabled
      ✔ Will return undefined if the passed mode is already the image's mode
      ✔ Will still update the mode of an initialized image with suppressToolbar: true
  L.EditHandle
    #calculateAngleDelta
      ✔ Should return 0 when given the same latlng twice.
    #_calculateScalingFactor
      ✔ Should return 1 when given the same latlng twice.
      ✔ Should return a smaller value as the 2nd latlng gets closer to the images original center.
  L.MatrixUtil
    .multmm
      ✔ Should act as the identity when the identity matrix is on the left.
      ✔ Should act as the identity when the identity matrix is on the right.
    .multsm
      ✔ Should scale the identity matrix.
    .general2DProjection
      ✔ Should return the 3*3 identity matrix when each corner is mapped back to itself.
      ✔ Should return a scalar multiple of the 3*3 identity matrix when the image is scaled.

Finished in 3.55 secs / 0.522 secs @ 18:56:39 GMT-0700 (Pacific Daylight Time)

SUMMARY:
✔ 80 tests completed
ℹ 2 tests skipped

Done.
```

**Comment by calvincodes** [comment]
@sashadev-sky Requesting review for this PR.

**Comment by calvincodes** [comment]
@sashadev-sky ^ Reminding again for the review :)

**Comment by calvincodes** [comment]
@sashadev-sky Any updates?

**Comment by sashadev-sky** [comment]
@calvincodes yeah the CI is non-deterministically failing. Don't worry about it not passing there, I will trigger a rebuild manually once this is ready to merge

**Comment by calvincodes** [comment]
@sashadev-sky Thanks for getting back. I didn't understand committing the `dist` file part. On my current branch, `git status` reports `nothing to commit, working tree clean`.

Also, I went through some of the similar PRs (https://github.com/publiclab/Leaflet.DistortableImage/pull/610) and I don't see any `dist` file committed there as well.

**Comment by sashadev-sky** [comment]
@VladimirMikulic @jywarren sorry i was away from the project for so long I do not even remember now. Did we stop committing the dist file?

**Comment by VladimirMikulic** [comment]
@sashadev-sky we still commit it :(

**Comment by calvincodes** [comment]
If required, how can I commit the same? I can not see it in `git status` result.

**Comment by VladimirMikulic** [comment]
@calvincodes you need to run `npm build` :)

**Comment by calvincodes** [comment]
> @calvincodes you need to run `npm build` :)

@VladimirMikulic: You mean `npm run build`?

I tried `npm build` and it throws this error:
```
➜  Leaflet.DistortableImage git:(redoing-update-l.map.doubleclickzoon.js-method-creation-to-es6-syntax) npm build
npm WARN build `npm build` called with no arguments. Did you mean to `npm run-script build`?
```

Also, after running `npm run build`, I am not getting any untracked filed in `git status`.

**Comment by VladimirMikulic** [comment]
@calvincodes that's right.

**Comment by calvincodes** [comment]
> @calvincodes that's right.

@VladimirMikulic But even after running `npm run build`, I am not getting any untracked filed in `git status`. 😕 Am I missing something here?

**Comment by VladimirMikulic** [comment]
@calvincodes I think no, you don't. You've simply converted old function syntax to ES6 method syntax, but the output that Babel produces is the same, regardless. That's why you don't see any changes.

**Comment by sashadev-sky** [comment]
@VladimirMikulic @calvincodes Sorry!!! I have been away from the repo for a while and was being an air head didn't consider that the code was still the same as far as the `dist` file is concerned. The travis repository moved to a different location on travis so I can't restart the build - just going to merge here. Thanks for your work

**Comment by calvincodes** [comment]
Thanks @VladimirMikulic @sashadev-sky for all your help. Glad to make this contribution 😀

**Pull request merged**
