### PR TITLE
changed var to let & const in DeleteAction.js

### PR DESCRIPTION
**Pull request by ijayhub**
Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [ ] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Review by PeculiarE — CHANGES_REQUESTED** [review]
Hi IJ! This looks great. Could you please remove the `package.json`, `package-lock.json`, and `leaflet.distortable image.js` files from your PR? Only the `DeleteAction.js` file should be changed. Thank you!

**Comment by PeculiarE** [comment]
Notice how the `DeleteAction.js` file is the only changed in your closed PR here: https://github.com/publiclab/Leaflet.DistortableImage/pull/1119/files

**Comment by PeculiarE** [comment]
One more thing: in the description above, please link your PR to the original issue. Thank you!

**Comment by ijayhub** [comment]
Ok I will

**Comment by ijayhub** [comment]
> One more thing: in the description above, please link your PR to the original issue. Thank you!

please I don't get.
but here is my URL: https://github.com/publiclab/Leaflet.DistortableImage/pull/1124 of pr.

**Comment by PeculiarE** [comment]
Hi @ijayhub...you were supposed to remove the changes you made to those files so they won't be part of your PR, not delete them totally from the codebase.

Please, un-delete them as they're vital to the codebase.

At this point, I'd suggest starting afresh and making a new PR. Before you commit, check to ensure that the only file with changes is the `DeleteAction.js` file.

Like I stated earlier, your first PR that you closed here: https://github.com/publiclab/Leaflet.DistortableImage/pull/1119 is a perfect example of what is being requested.

Thank you!

**Comment by ijayhub** [comment]
Have done the right thing please recheck.

**Comment by PeculiarE** [comment]
Where should I check? @ijayhub....please provide a link or tag me in the new PR

**Comment by ijayhub** [comment]
I sent the link to the public chat room ... But I will resend it again my
system is off now

**Comment by PeculiarE** [comment]
Never mind, Tilda has reviewed it already. Well done!

**Comment by ijayhub** [comment]
Good morning, I had to start afresh as u said.
Please what next?
Thank you

**Pull request closed without merging**
