### PR TITLE
Various toolbar updates

### PR DESCRIPTION
**Pull request by sashadev-sky**
references #158, #27 , #126, publiclab/mapknitter#300

**Status:**

1) In my previous PR #158 I added deselection on map click, but this did not work for the RotateHandles. Deselection might have not worked at all actually. Sorry for this bug! This is now fixed. 

2) When the toolbar icon swaps between the DistortHandles and RotateHandles, the actual icon does not update until you click on the image. This is now fixed. (See below)

3) change rotate/distort icons in Toolbar when using hotkeys #27 - fixed (find gif in issue)

### CODE REVIEW

**Comment by sashadev-sky** [comment]
gifs for Point 2 Toolbar icons:
Before:
tool-icons

After:
tool-icons2

**Comment by sashadev-sky** [comment]
**gifs for Point 3 Toolbar positioning:**
In this gif I am just highlighting how even if you click the image, showing the toolbar, at a very zoomed out level, it will still be in the same scaled position when you zoom back in.
tool6

**Comment by sashadev-sky** [comment]
@jywarren please advice if you like this solution for toolbar positioning. I would just pull my PR and check it locally so you can really play around with it.

Also if you have any thoughts on the pending section that would be great! Thank you!!

**Comment by sashadev-sky** [comment]
@rexagod looping you in :)

**Comment by rexagod** [comment]
@jywarren @sashadev-sky This looks interesting!  I just wanted to chime in here for a second to let you all know that unfortunately it's exams week currently and therefore I'll be busy. But nonetheless, working on this library will be my first priority from the next week on!

It's great to see your work here @sashadev-sky! :+1: :raised_hands:

Thanks all!

**Comment by jywarren** [comment]
This looks awesome. Ready to merge? Thanks!!!

Good luck with exams @rexagod!!

**Comment by sashadev-sky** [comment]
@jywarren I still need to clean up the code should be quick, but there is another issue with it wanted to fix before... I need to play around with it a little more to decide what to do but let me know if you have any ideas! 

1) Anchoring the toolbar to the higher handle might not work well if someone pulls one of the handles way above another so need to take into consideration a limit at which the toolbar stops moving up
2) dealing with the toolbar overlapping with another handle - was thinking maybe checking how changing the z-index of both would look, or again creating some kind of limit but this time for how close the toolbar can get to any handle
3) want to see how it would look if the toolbar location changes dynamically when moving handles

**Comment by sashadev-sky** [comment]
@jywarren @rexagod what do you guys think of using "doubleclick" to change the z-index of the toolbar if toolbar does overlap with a marker? Then if you "click" on the image it goes back to normal. The rest of the toolbar still works with this z-index change just not the corner button that will become overlapped.

An overlap between the marker and toolbar where you can't grab the marker at all happens only in the small radius of a specific angle / distance between the top markers.

Is this a good way to handle this or making too many complicated rules for the UI? Should it be documented anywhere besides tests if we use it?

toolbar-zindex

**Comment by jywarren** [comment]
Hmm, this is a tough one. What if the menu sort of "runs away" upwards if you're about to hit it? Like, we essentially make a rule that it can't be lower than any handle. Is that what you were suggesting before?

**Comment by sashadev-sky** [comment]
@jywarren Yes I was thinking about that, but then what if for ex. the top right corner is way higher than the top left? Then the toolbar would be unnecessarily high. 

The issue is that the toolbar could just appear on top of the marker and cover enough of it where you can't grab it at all. Dragging the marker through the toolbar (placing it under or past it) works regardless of z-index.I think this bug is present in the current toolbar as well.

I'll see if I can figure out another way. I can implement some logic to check if it overlaps and if it does move it but then the issue will be calculating whether moving up or down is appropriate? Also was thinking about it angling it at the slope of the markers, also not ideal because of edge cases

**Comment by sashadev-sky** [comment]
@jywarren ok here is the only alternative I could think of. If you like it I can clean it up (make the icons rotate when it gets to a point that its almost vertical, make a formula for updating the tooltips position that's less hardcoded and more accurate). 

This calculates the angle between the top two markers and if its greater than 0, applies that angle to the toolbar with css `transform: rotate`.

Even though I made it I think it is a little annoying 😅but I also was looking at it for a long time
toolbar-fix-alt
:

**Comment by sashadev-sky** [comment]
@jywarren two other options for the same implementation that are potentially a lot better. 

1) hide the toolbar `onHandleDragStart` and the user clicks on the image to indicate they are done distorting and show it again.
toolbar-fix-alt-3

2) re-show the toolbar also on `handleDragEnd` (would be consistent with how toolbar hide and show works for dragging the whole image):
toolbar-fix-alt-2

**Comment by sashadev-sky** [comment]
@jywarren What are your thoughts on this approach:
(would also add turning the icons when the toolbar is almost vertical and maybe the toolbar disappearing on `handleDragStart` and not reappearing again until image click, or only updating its position on image click)
Note the toolbar will glitch during zoom like the image itself and the other markers. I tested this glitch can be prevented completely by passing `zoomAnimation: false` to the Map but that would be a whole separate issue

toolbar-fix-alt-5

**Comment by jywarren** [comment]
OMG Sasha this is amazing but also it made me just laugh out loud... 😆 

Somehow we never think of the internet as being rotate-able! 🤣 🙃 

OK, we can try this out... how hard would it be to make this a setting -- people could go with the "unnecessarily high" solution - i.e. it'll drift away from the image if it's really distorted, OR the "rotatable toolbar" version, if they like that?

Second, with the rotatable version, does it start up being rotated when you click it after deselecting? 

Third, what if you rotate the whole image 180 degrees, does it make the menu appear upside down? That could be trouble. 

Finally, the original request to open the menu wherever you'd clicked on the image to select it could give the user some flexibility and a way to work around edge cases? 

I'd say -- let's go with non-rotation as a default, whether that means it gets pushed up really high when it's highly distorted, or whether that means it's "where you clicked to select it". Let's work on the variations on this UI in a separate PR to not block the rest of the work here. If it's easy to make it switch-able, we can do that. But otherwise let's just stash the code for the variants and go with the simplest UI even if it has some compromises! 

Thanks Sasha, this is really awesome to see. I love these gifs 📸 👍

**Comment by jywarren** [comment]
And, this should be good to merge once we address that! Thank you!!!

**Comment by jywarren** [comment]
One last thing - re: toolbar appearing off screen, we could consider either a) panning the map up so you can see it, or b) limiting how high it can go so it cannot be displayed off-screen? Just some ideas.

**Comment by sashadev-sky** [comment]
Yes the gif somehow came out looking like a `distortableImage` monster pushing over a clumsy toolbar 😅 😅. Definitely keep this gif.

1) I don't think that will be hard but I will not be able to do it at this very moment 

2) Yes it appears immediately in the position it should based on the angle of the markers. In the comment I marked "outdated" [above](https://github.com/publiclab/Leaflet.DistortableImage/pull/187#issuecomment-480152522), the first gif demonstrates this

3) upside down case looks like this: not that bad of a bug and will be easy to fix
Screen Shot 2019-04-05 at 2 52 13 PM

4) Yes I agree. The demo I referenced for point 2 also demonstrates what it would look like if `onHandleDrag` hides the toolbar and only on image click it comes back. Because the user does not need the toolbar while they are distorting anyway this makes sense. 
   -  For the edge cases: I have found that there are not that many. The toolbar seems to hold its ground in a reasonable way regardless of what you do with the markers. And small things like upside down will be easy to fix. The part where its fumbling around is not really introducing a new bug but more part of the general image distortion bug if that makes sense

5) non-rotating ui - It will actually be easier and faster for me to complete the rotating one and then open a new issue for the rest because each take some thought. 

**How about I just take, from the PR description, the first 3 points: icon-changing, icon-changing-hotkeys and deselection with rotating handles. And take out all the rest and move it into a new PR?**

**Comment by sashadev-sky** [comment]
Those extra 2 points I will move into the new PR as well - I will make my PR description list as usual and put them there

**Comment by jywarren** [comment]
That'd be great, splitting this up. Then we can move forward without it
blocking. Thanks!!!

**Comment by sashadev-sky** [comment]
@jywarren this is ready to merge. Fixed here are the 3 issues we agreed to leave, mentioned in the PR description. double-checked that only these relevant updates are made here and they still work. 

I moved everything else - including comments and gifs into #201 so you can see clearly what is related to this PR. I'll worry about rebasing #201 later 😅

**Pull request merged**
