### PR TITLE
Update leaflet.distortableimage.css with narrow scope selectors

### LINKED ISSUE #330: CSS selectors without class or id in v0.6.0
**Describe the bug:**
In leaflet.distortableimage.css, several CSS selectors include only HTML tags and no cleaner selectors such as class or id. As a result, these styles sometimes override other CSS styles you have in your app or website.

**Reproduce the behavior:**
Have a look to leaflet.distortableimage.css in dist folder, especially these CSS selectors: 
- svg
- td
- th
- kbd

**Browser, version, and operating system:**
- Browsers : Firefox 67, Chrome 75
- Leaflet DistortableImage v0.6.0
- Operating system: Windows 10

### PR DESCRIPTION
**Pull request by jywarren**
fixes #330 (thanks for reporting!)

### CODE REVIEW

**Comment by jywarren** [comment]
So examples (and new syntax) is now:

`<div id="map" class="ldi" style="width:100%; height:100%; position:absolute; top:0;"></div>`

cc @sashadev-sky @rexagod -- thanks @flopail does this work for you?

**Comment by jywarren** [comment]
@sashadev-sky this may break a few UI elements that are not within the `map` element, but they will work if they also get the `.ldi` class (although we may have to put a container around them or change the style selector to `.ldi.whatever`).

**Comment by jywarren** [comment]
OK we'll need to compile https://github.com/publiclab/Leaflet.DistortableImage/commit/84861a00e6f144b4171a447fb9ec2cb2088fcedd to get the styles working again unless that was added inside the map element, which it might've been?

**Comment by jywarren** [comment]
Hi, @sashadev-sky, we discussed this but I think it's almost done - we may just need to compile and add to the docs to tell people to add this classname to the container element, like:

```html
<div id="map" class="ldi" style="width:100%; height:100%; position:absolute; top:0;"></div>
```

Do you think you could double check that this all works, to confirm, and then we can merge this? Thanks!

**Comment by sashadev-sky** [comment]
@jywarren totally forgot to update the docs to reflect the change to the map class! I will open a PR for that tomorrow

I implemented everything else in here in #353 which you merged :) but i will wait until after docs update to close the issues

**Comment by sashadev-sky** [comment]
@jywarren also when I bump new version in mapknitter I will make sure that the appropriate classes are added where necessary, like for map setup

**Comment by jywarren** [comment]
super duper. thanks!

**Pull request closed without merging**
