### PR TITLE
replaced var keyword with const

### PR DESCRIPTION
**Pull request by Ranecodes**
Fixes #1086 (MapMixins.js)
Screenshot 2022-10-11 003914
Screenshot 2022-10-11 003854

I replaced the "var" keywords with "const". Kindly review my pull request and please let me know if there is anything I need to change. Thanks!

### CODE REVIEW

**Comment by TildaDares** [comment]
Thank you for the review @sainamercy!

**Comment by TildaDares** [comment]
Congratulations on merging your PR @Ranecodes 🎉

**Comment by Ranecodes** [comment]
> 

Thanks for the review @sainamercy!

**Comment by Ranecodes** [comment]
> Congratulations on merging your PR @Ranecodes 🎉

Thank you @TildaDares!

**Pull request merged**
