### PR TITLE
Update L.DragHandle initializer to class factory syntax

### PR DESCRIPTION
**Pull request by Alpha-yoyo**
Fixes https://github.com/publiclab/Leaflet.DistortableImage/issues/582

Update L.DragHandle initializer to class factory syntax

### CODE REVIEW

**Comment by Alpha-yoyo** [comment]
Hi @sashadev-sky , can you review it please? thank you

**Comment by Alpha-yoyo** [comment]
Hi @sashadev-sky how do you commit the dist file?

**Comment by sashadev-sky** [comment]
the `dist` file is automatically updated for you if you have the dev server running in the background. But you can build it with `$ npm run build` and then you should see it updated and commit it. If it commits the one w/ 14k changes then re-commit again.

**Comment by sashadev-sky** [comment]
@Alpha-yoyo Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by sashadev-sky** [comment]
Hi! Sorry about this, but we close FTOs if a week goes by with no updates or replies because we assume they have been abandoned. This is to give other contributors a change, as these types of issues are high in demand now. 

If you'd like to try again with a new FTO, we welcome you to!

**Pull request closed without merging**
