### PR TITLE
Update package.json 

### PR DESCRIPTION
**Pull request by WagnerLoc**
Update package.json to be compliant with npm naming https://docs.npmjs.com/files/package.json

### CODE REVIEW

**Comment by justinmanley** [comment]
looks good to me! 👍

**Comment by jywarren** [comment]
Thanks!!!

**Comment by justinffs** [comment]
Note that this is a breaking change for anyone using a module bundler like webpack.

**Comment by jywarren** [comment]
Is it? Shall I unpublish and ought this then to become v1.0.0 (reluctance)?

**Comment by jywarren** [comment]
Uhhh - apologies, I didn't realize, but I don't believe Justin had published this previously. I'm not clear on whether webpack will consider it a breaking change if it's the first entry in the npm registry? Presumably people had been pointing it at a specific commit on github, or otherwise locally copying in the code before bundling it.

**Comment by jywarren** [comment]
Indeed: `available-versions` (https://www.npmjs.com/package/available-versions) shows:

```
$ releases leaflet-distortableimage
leaflet-distortableimage from git+https://github.com/publiclab/Leaflet.DistortableImage.git
-------------------------------------------------------------------------------------------
version  age         dist-tag
-------  ----------  --------
0.0.11   11 minutes  latest  
```

I'm happy to unpublish this, but i'm not clear on the semver ramifications. Willing to hear folks' input on `v1.0.0` vs. `v0.0.12` vs. leaving it as-is.

**Comment by justinffs** [comment]
@jywarren what do you mean by publish?  Do you mean publish to NPM?  I can not find `leaflet-distortableimage` anywhere on npm, and npm also no longer allows anything to be unpublished.

**Comment by jywarren** [comment]
yes, npm -- i believe it takes a little while to show up, but it's there
now: https://www.npmjs.com/package/leaflet-distortableimage

**Pull request merged**
