### PR TITLE
Replaced `var` keyword with `const` in RotateHandle.js

### PR DESCRIPTION
**Pull request by Tammy-Ajoko**
Fixes #1086

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [@TildaDares ] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Review by jywarren — APPROVED** [review]

**Comment by jywarren** [comment]
Great work, thank you so much!!

**Comment by jywarren** [comment]
@TildaDares i think i may have missed something here and will address in https://github.com/publiclab/Leaflet.DistortableImage/pull/1097, my apologies!

**Comment by jywarren** [comment]
Actually I think i need help answering this. I second guessed my approving this PR with only `const`, and modified it to use some `let`. But since `const` scope is only within the block and we finish using all these values within the scope of   `_onHandleDrag()`, I think maybe @Tammy-Ajoko was correct and all of these can be `const`. @TildaDares do you think that's correct? If so, @Tammy-Ajoko my apologies for changing part of this. If you'd like, and @TildaDares agrees, you could change them back to `const` in a new PR and let us know in the chatroom.

I guess I'm also still adjusting to ES6!! 😅

**Comment by Tammy-Ajoko** [comment]
> Great work, thank you so much!!

Thank you very much, and thank you for the changes as well 😊

**Comment by TildaDares** [comment]
You're right @jywarren. Also if the variable declared with `const` is changed in the function that it was passed to, it would not raise an error because the variable is passed by value and not reference.

**Comment by Tammy-Ajoko** [comment]
> You're right @jywarren. Also if the variable declared with `const` is changed in the function that it was passed to, it would not raise an error because the variable is passed by value and not reference.

@TildaDares @jywarren Sorry does this mean I should make another PR and change it to const or not.

**Comment by jywarren** [comment]
Hi @Tammy-Ajoko yes you can do that, if you can please add a link to this PR so that others can see our reasoning, that would be great. Thank you and sorry for the confusion!

**Pull request merged**
