### PR TITLE
Show/hide sidebar functionality

### PR DESCRIPTION
**Pull request by 7malikk**
Fixes #[1172](https://github.com/publiclab/Leaflet.DistortableImage/issues/1172) 

Co-authored by: @segun-codes 

### GIF
toggle-btn-main

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [x] code is in a uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updates
* [x] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by 7malikk** [comment]
@jywarren Hello there, kindly take a look at my PR.

The initial icon on the map interface needs a distinct color, but anytime I use bootstrap or CSS. The icon disappears or becomes a lot more opaque.

What do you propose I do to resolve this?

**Comment by 7malikk** [comment]
@jywarren fixed the disappearing icon

**Comment by jywarren** [comment]
Hi @7malikk - this looks really good. I am not sure if we need to have the ability to close the first modal, though... can you do anything if you don't use that modal? What do you think, maybe it's enough to have it on the sidebar only?

**Comment by 7malikk** [comment]
> Hi @7malikk - this looks really good. I am not sure if we need to have the ability to close the first modal, though... can you do anything if you don't use that modal? What do you think, maybe it's enough to have it on the sidebar only?

Thanks @jywarren It was a joint effort with @segun-codes .
Concerning the modal, we added some functionalities I think you will like. 
After which you can make some corrections and/or suggestions.

**Comment by segun-codes** [comment]
> > > Hi @7malikk - this looks really good. I am not sure if we need to have the ability to close the first modal, though... can you do anything if you don't use that modal? What do you think, maybe it's enough to have it on the sidebar only?
> > 
> > 
> > Thanks @jywarren It was a joint effort with @segun-codes . Concerning the modal, we added some functionalities I think you will like. After which you can make some corrections and/or suggestions.
> 
> @7malikk, yes, we did add functionalities @jywarren will appreciate. Could you also show GIF illustrating that we have also implemented the functionality to close the sidebar by clicking on the map. Love the GIFs, thanks...

**Comment by 7malikk** [comment]
@jywarren @TildaDares 
Final touches have been made, here's the final commit
Any suggestions/corrections will be appreciated

It was the joint effort of @segun-codes and I
And to be honest it was fun

**Comment by 7malikk** [comment]
> > > > Hi @7malikk - this looks really good. I am not sure if we need to have the ability to close the first modal, though... can you do anything if you don't use that modal? What do you think, maybe it's enough to have it on the sidebar only?
> > > 
> > > 
> > > Thanks @jywarren It was a joint effort with @segun-codes . Concerning the modal, we added some functionalities I think you will like. After which you can make some corrections and/or suggestions.
> > 
> > 
> > @7malikk, yes, we did add functionalities @jywarren will appreciate. Could you also show GIF illustrating that we have also implemented the functionality to close the sidebar by clicking on the map. Love the GIFs, thanks...

That functionality is in the second GIF @segun-codes

**Comment by segun-codes** [comment]
> > > > > Hi @7malikk - this looks really good. I am not sure if we need to have the ability to close the first modal, though... can you do anything if you don't use that modal? What do you think, maybe it's enough to have it on the sidebar only?
> > > > 
> > > > 
> > > > Thanks @jywarren It was a joint effort with @segun-codes . Concerning the modal, we added some functionalities I think you will like. After which you can make some corrections and/or suggestions.
> > > 
> > > 
> > > @7malikk, yes, we did add functionalities @jywarren will appreciate. Could you also show GIF illustrating that we have also implemented the functionality to close the sidebar by clicking on the map. Love the GIFs, thanks...
> 
> That functionality is in the second GIF @segun-codes

@7malikk, you are correct. It seems to me that this went well for us, thanks.

**Comment by 7malikk** [comment]
@jywarren @TildaDares hello, could you review my PR?

**Comment by segun-codes** [comment]
> @jywarren @TildaDares hello, could you review my PR?

@jywaren @TildaDares, this PR is still awaiting your review. Could you kindly attend to it, many thanks.

**Comment by 7malikk** [comment]
@jywarren Kindly review our PR

**Comment by jywarren** [comment]
Hi, thank you! I am wondering if we are creating more code than necessary. Could it be simpler to just not allow the first modal to be bypassed if no link is present? That would be a lot less code. 

Actually I think we should try to address things in separate PRs, because I see that the code to make a "minimize sidebar" functionality is already done. That could be merged on its own. But the second question of the additional notification and the initial state upon load, we need some more time to think about that and what is the most efficient way forward. This is a really good reason to do just one thing in each PR, so that some things don't get blocked by others -- does that make sense? If you'd like, we can remove everything except the sidebar closing code in this PR, merge it, and continue discussing additional features in a separate PR? What do you think?

**Comment by 7malikk** [comment]
@jywarren Alright this sounds good.

So if I get you right we should address the following:

- In this PR the side bar should be able to be shown hidden. 

- In a new PR we work on the notification

- In another PR, we work on not allowing the welcome modal be bypassed 

Is this alright @jywarren?

**Comment by segun-codes** [comment]
> Hi, thank you! I am wondering if we are creating more code than necessary. Could it be simpler to just not allow the first modal to be bypassed if no link is present? That would be a lot less code.
> 
> Actually I think we should try to address things in separate PRs, because I see that the code to make a "minimize sidebar" functionality is already done. That could be merged on its own. But the second question of the additional notification and the initial state upon load, we need some more time to think about that and what is the most efficient way forward. This is a really good reason to do just one thing in each PR, so that some things don't get blocked by others -- does that make sense? If you'd like, we can remove everything except the sidebar closing code in this PR, merge it, and continue discussing additional features in a separate PR? What do you think?

@jywarren, okay, thank you.

**Comment by segun-codes** [comment]
> @jywarren Alright this sounds good.
> 
> So if I get you right we should address the following:
> 
> * In this PR the side bar should be able to be shown hidden.
> * In a new PR we work on the notification
> * In another PR, we work on not allowing the welcome modal be bypassed
> 
> Is this alright @jywarren?

Hi @7malikk, based on @jywarren's advice I think we should just retain the code for hiding and displaying the sidebar (including the functionality to hide sidebar by clicking on the map) for this PR. Any other feature can be a subject of another discussion in a separate issue/PR.

**Comment by 7malikk** [comment]
> > @jywarren Alright this sounds good.
> 
> > 
> 
> > So if I get you right we should address the following:
> 
> > 
> 
> > * In this PR the side bar should be able to be shown hidden.
> 
> > * In a new PR we work on the notification
> 
> > * In another PR, we work on not allowing the welcome modal be bypassed
> 
> > 
> 
> > Is this alright @jywarren?
> 
> 
> 
> Hi @7malikk, based on @jywarren's advice I think we should just retain the code for hiding and displaying the sidebar (including the functionality to hide sidebar by clicking on the map) for this PR. Any other feature can be a subject of another discussion in a separate issue/PR.

I agree @segun-codes 

I'll make those changes and push them.

While you can create the issue, do we can discuss on the next steps forward.

**Comment by segun-codes** [comment]
> > > @jywarren Alright this sounds good.
> > 
> > 
> > > 
> > 
> > 
> > > So if I get you right we should address the following:
> > 
> > 
> > > 
> > 
> > 
> > > * In this PR the side bar should be able to be shown hidden.
> > 
> > 
> > > * In a new PR we work on the notification
> > 
> > 
> > > * In another PR, we work on not allowing the welcome modal be bypassed
> > 
> > 
> > > 
> > 
> > 
> > > Is this alright @jywarren?
> > 
> > 
> > Hi @7malikk, based on @jywarren's advice I think we should just retain the code for hiding and displaying the sidebar (including the functionality to hide sidebar by clicking on the map) for this PR. Any other feature can be a subject of another discussion in a separate issue/PR.
> 
> I agree @segun-codes
> 
> I'll make those changes and push them.
> 
> While you can create the issue, do we can discuss on the next steps forward.

Hi @7malikk, consistent with @jywarren's thought I have started wondering if there's indeed any need for the notification? Is it worth really opening an issue for it, especially as the need for it is not obvious?

**Comment by 7malikk** [comment]
@segun-codes I was of similar thought, over time we could include said feature. For now, we could just leave the show and hide as @jywarren suggested

**Comment by segun-codes** [comment]
> @segun-codes I was of similar thought, over time we could include said feature. For now, we could just leave the show and hide as @jywarren suggested

Okay, so let's give this PR a final landing. Many thanks @7malikk @jywarren.

**Comment by segun-codes** [comment]
> Hi, thank you! I am wondering if we are creating more code than necessary. Could it be simpler to just not allow the first modal to be bypassed if no link is present? That would be a lot less code.
> 
> Actually I think we should try to address things in separate PRs, because I see that the code to make a "minimize sidebar" functionality is already done. That could be merged on its own. But the second question of the additional notification and the initial state upon load, we need some more time to think about that and what is the most efficient way forward. This is a really good reason to do just one thing in each PR, so that some things don't get blocked by others -- does that make sense? If you'd like, we can remove everything except the sidebar closing code in this PR, merge it, and continue discussing additional features in a separate PR? What do you think?

@jywarren, I agree with you. Thank you for taking the time to explain this to us.

**Comment by 7malikk** [comment]
@jywarren I've made the changes for this PR. The GIF shows the current functionality.

**Comment by jywarren** [comment]
This is looking almost ready -- i think there's just one more step; can you re-run the build dist files, and add your updates to resolve the conflict? Thanks!!

**Comment by 7malikk** [comment]
> This is looking almost ready -- i think there's just one more step; can you re-run the build dist files, and add your updates to resolve the conflict? Thanks!!

Will do @jywarren 
Thanks so much for the feedback

**Comment by 7malikk** [comment]
@jywarren I re-ran the build to update the dist, is this accurate??
@segun-codes what do you think? am i on the right path?

**Comment by segun-codes** [comment]
> @jywarren I re-ran the build to update the dist, is this accurate?? @segun-codes what do you think? am i on the right path?

Looks good to me @7malikk, thanks.

**Comment by segun-codes** [comment]
Hi @jywarren, could you kindly review the PR. Many thanks!

**Comment by jywarren** [comment]
OK, I just dropped the dist changes again -- my commands were:

```sh
cd dist
wget https://raw.githubusercontent.com/publiclab/Leaflet.DistortableImage/main/dist/leaflet.distortableimage.js
cd ../
git add dist
git commit -m 'removed dist changes'
git push
```

Sorry i missed the opportunity and had to do it a second time! Had a lot of work commitments the past few days but am catching up now!

**Comment by 7malikk** [comment]
> OK, I just dropped the dist changes again -- my commands were:
> 
> 
> 
> ```sh
> 
> cd dist
> 
> wget https://raw.githubusercontent.com/publiclab/Leaflet.DistortableImage/main/dist/leaflet.distortableimage.js
> 
> cd ../
> 
> git add dist
> 
> git commit -m 'removed dist changes'
> 
> git push
> 
> ```
> 
> 
> 
> Sorry i missed the opportunity and had to do it a second time! Had a lot of work commitments the past few days but am catching up now!

Oh, alright @jywarren I suspected

**Comment by jywarren** [comment]
Excellent! Thank you!!!!

**Comment by segun-codes** [comment]
> Excellent! Thank you!!!!

Many thanks @jywarren @7malikk. I am grateful this is now behind us.

**Pull request merged**
