### PR TITLE
Create select.js

### PR DESCRIPTION
**Pull request by Leeiaisabelle**
Create select.js for inline JavaScript that was removed from [select.html](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/examples/select.html).

Resolves: #1185

Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [ ] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Review by TildaDares — CHANGES_REQUESTED** [review]
Hi @Leeiaisabelle, the changes in this PR AND #1255 should be in a single PR. Also, please remove the additional plus signs you added in the code. Thanks!

**Comment by segun-codes** [comment]
> Hi @Leeiaisabelle, the changes in this PR AND #1255 should be in a single PR. Also, please remove the additional plus signs you added in the code. Thanks!



> Create select.js for inline JavaScript that was removed from [select.html](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/examples/select.html).
> 
> Resolves: #1185
> 
> Fixes #0000 (<=== Add issue number here)
> 
> Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!
> 
> * [ ]  PR is descriptively titled 📑 and links the original issue above 🔗
> * [ ]  tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
> * [ ]  code is in uniquely-named feature branch and has no merge conflicts 📁
> * [ ]  screenshots/GIFs are attached 📎 in case of UI updates
> * [ ]  @mention the original creator of the issue in a comment below for help or for a review
> 
> > We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!
> 
> If tests do fail, click on the red `X` to learn why by reading the logs.
> 
> Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
> 
> Thanks!

Hi @Leeiaisabelle, great job so far, thanks! Have you need for help to finalize this PR as advised by @TildaDares ?

**Comment by segun-codes** [comment]
Hello @Leeiaisabelle, still awaiting your response to enable us give final landing to this PR.

**Comment by cesswairimu** [comment]
Thanks for attempting  this @Leeiaisabelle , it was jointly resolved on https://github.com/publiclab/Leaflet.DistortableImage/pull/1291,  Closing this

**Pull request closed without merging**
