### PR TITLE
changed variable declarations from var to let

### PR DESCRIPTION
**Pull request by Lovelyfin00**
Fixes #1086  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [ ] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

@TildaDares 
Please review
Thanks

### CODE REVIEW

**Comment by sainamercy** [comment]
Hi, @Lovelyfin00. In lines 3, 4, and 31 you should use "const" instead of "let" since the values are not meant to be changed

**Comment by Lovelyfin00** [comment]
Thamks 
Done that

**Comment by sainamercy** [comment]
replace "Fixes #0000 (<=== Add issue number here)" above  with   issue 1086.
then tag a mentor here to review your PR

**Comment by TildaDares** [comment]
Thank you for the reviews @sainamercy!

**Comment by TildaDares** [comment]
Hi @Lovelyfin00, the change is still there.

**Comment by Lovelyfin00** [comment]
Should I close this PR and open another one? @TildaDares

**Pull request closed without merging**
