### PR TITLE
Implement Functionality to Restore welcomeModal

### LINKED ISSUE #1294: Functionality to Restore welcomeModal to View
There's currently no way to restore welcomeModal to view when closed by clicking the `begin` or `close button`. A user must therefore refresh/reload archive.html to restore it to view, whereas this approach is appropriate in the event of an uncontrolled error on the webpage, it is however counterintuitive in the case of the above stated use cases.

**Please describe the desired behavior.**
Implement functionality that extends the use case of the `stack button` icon already present on `archive.html` to support restoring the welcomeModal to view and focus.

**Additional context (optional)**
See screenshot below for more insight on the issue.

Screenshot-2

### PR DESCRIPTION
**Pull request by segun-codes**
Fixes #1294  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updates
* [x] @mention the original creator of the issue in a comment below for help or for a review

See the screenshot below.
screen-capture_1

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by segun-codes** [comment]
Work still in progress on this PR.

**Comment by segun-codes** [comment]
While fixing the task in this PR, I observed the need for the following:

1. Refactor code in archive.js to eliminate duplicate `welcomeModal.addEventListener('hidden.bs.modal', ...`.
2. In the case of multiple fetch episodes (e.g., fetch 24images from a given URL and then fetch 1image from another URL), the most recently fetched image should be first on the list. Re-sorting of fetched images on the sidebar is needed.
3. At what point should fetched images be wiped out from sidebar? This question becomes relevant when images are fetched from multiple sources or different images from same source. The sidebar becomes packed with images and may begin to degrade the efficiency of the service.
4. The search bar fails to work any time the sidebar is closed (and remains in closed state) by clicking the tile. However, this is not the case when sidebar is closed using "View Map" button.

@jywarren, @cesswairimu, @TildaDares, @PeculiarE, @7malikk... what do you think about at least item #3 above?

If this observation makes sense to you, I could wrap all these in one or two issues then proceed to fix them alone or jointly with @7malikk since item #3 is quite related to the fetching thumbnail task he's currently working on. 

Many thanks!

**Comment by segun-codes** [comment]
> While fixing the task in this PR, I observed the need for the following:
> 
> 1. Refactor code in archive.js to eliminate duplicate `welcomeModal.addEventListener('hidden.bs.modal', ...`.
> 2. In the case of multiple fetch episodes (e.g., fetch 24images from a given URL and then fetch 1image from another URL), the most recently fetched image should be first on the list. Re-sorting of fetched images on the sidebar is needed.
> 3. At what point should fetched images be wiped out from sidebar? This question becomes relevant when images are fetched from multiple sources or different images from same source. The sidebar becomes packed with images and may begin to degrade the efficiency of the service.
> 4. The search bar (on `archive.html`) fails to work any time the sidebar is closed (and remains in closed state) by clicking the tile. However, this is not the case when sidebar is closed using "View Map" button.
> 
> @jywarren, @cesswairimu, @TildaDares, @PeculiarE, @7malikk... what do you think about at least item #3 above?
> 
> If this observation makes sense to you (and after your inputs), I could wrap all these in one or two issues then proceed to fix them alone or jointly with @7malikk since item #3 is quite related to the fetching thumbnail task he's currently working on.
> 
> Many thanks!

One option is to allow user decide when to clear the images/thumbnails on sidebar. Alternatively, we could apply a limit on the number of fetched images/thumbnails that can be placed on the sidebar so that the performance of the service is not impacted.

**Comment by 7malikk** [comment]
> While fixing the task in this PR, I observed the need for the following:
> 
> 1. Refactor code in archive.js to eliminate duplicate `welcomeModal.addEventListener('hidden.bs.modal', ...`.
> 2. In the case of multiple fetch episodes (e.g., fetch 24images from a given URL and then fetch 1image from another URL), the most recently fetched image should be first on the list. Re-sorting of fetched images on the sidebar is needed.
> 3. At what point should fetched images be wiped out from sidebar? This question becomes relevant when images are fetched from multiple sources or different images from same source. The sidebar becomes packed with images and may begin to degrade the efficiency of the service.
> 4. The search bar (on `archive.html`) fails to work any time the sidebar is closed (and remains in closed state) by clicking the tile. However, this is not the case when sidebar is closed using "View Map" button.
> 
> @jywarren, @cesswairimu, @TildaDares, @PeculiarE, @7malikk... what do you think about at least item #3 above?
> 
> If this observation makes sense to you (and after your inputs), I could wrap all these in one or two issues then proceed to fix them alone or jointly with @7malikk since item #3 is quite related to the fetching thumbnail task he's currently working on.
> 
> Many thanks!

This sounds like a good idea. I did encounter some issues #1295  in terms of efficiency when I imported a collection of 200+ images, it took a lot longer to fetch the images and some time to place them on the map.

That's my take on the third issue.

Concerning the 4th issue, the search bar is fully functional, have you pulled the latest changes?

**Comment by segun-codes** [comment]
@7malikk , yes I have. I'll chat you up on whatsapp.

**Comment by segun-codes** [comment]
> > While fixing the task in this PR, I observed the need for the following:
> > 
> > 1. Refactor code in archive.js to eliminate duplicate `welcomeModal.addEventListener('hidden.bs.modal', ...`.
> > 2. In the case of multiple fetch episodes (e.g., fetch 24images from a given URL and then fetch 1image from another URL), the most recently fetched image should be first on the list. Re-sorting of fetched images on the sidebar is needed.
> > 3. At what point should fetched images be wiped out from sidebar? This question becomes relevant when images are fetched from multiple sources or different images from same source. The sidebar becomes packed with images and may begin to degrade the efficiency of the service.
> > 4. The search bar (on `archive.html`) fails to work any time the sidebar is closed (and remains in closed state) by clicking the tile. However, this is not the case when sidebar is closed using "View Map" button.
> > 
> > @jywarren, @cesswairimu, @TildaDares, @PeculiarE, @7malikk... what do you think about at least item #3 above?
> > If this observation makes sense to you (and after your inputs), I could wrap all these in one or two issues then proceed to fix them alone or jointly with @7malikk since item #2 & 3 is quite related to the fetching thumbnail task he's currently working on.
> > Many thanks!
> 
> This sounds like a good idea. I did encounter some issues #1295 in terms of efficiency when I imported a collection of 200+ images, it took a lot longer to fetch the images and some time to place them on the map.
> 
> That's my take on the third issue.
> 
> Concerning the 4th issue, the search bar is fully functional, have you pulled the latest changes?

Okay, thanks for your thought @7malikk.

**Comment by jywarren** [comment]
Hi, thanks! For 3), I think perhaps we should not clear any images until we come up with a way to maintain a list of sources (that could be added into the export JSON perhaps?) -- otherwise folks may lose track of where they got images. So maybe we hold off on clearing images until we explore that in another issue? Thanks!

**Comment by segun-codes** [comment]
> Hi, thanks! For 3), I think perhaps we should not clear any images until we come up with a way to maintain a list of sources (that could be added into the export JSON perhaps?) -- otherwise folks may lose track of where they got images. So maybe we hold off on clearing images until we explore that in another issue? Thanks!

Okay, could you kindly review this PR, many thanks!

**Comment by 7malikk** [comment]
> Hi, thanks! For 3), I think perhaps we should not clear any images until we come up with a way to maintain a list of sources (that could be added into the export JSON perhaps?) -- otherwise folks may lose track of where they got images. So maybe we hold off on clearing images until we explore that in another issue? Thanks!

Sounds good @jywarren

**Comment by segun-codes** [comment]
Hi @jywarren, could you kindly review this PR and (possibly merge)?

Many thanks!

**Comment by segun-codes** [comment]
@7malikk as discussed, I will leave items #2 and 3 above to you as they are related to the task you are currently working on, then I will fix items #1 & 4 in a single issue. Cheers!

**Comment by jywarren** [comment]
👍🏽👍🏽✨✨

**Pull request merged**
