### PR TITLE
created function `renderImages` to handle image rendering

### PR DESCRIPTION
**Pull request by 7malikk**
Clean up archive.js - split image rendering functionality into a separate function

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [x] code is in a uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [x] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by 7malikk** [comment]
@jywarren, here i created the `renderImages` function we spoke about here: https://github.com/publiclab/Leaflet.DistortableImage/pull/1290#discussion_r1045103863

**Review by cesswairimu — APPROVED** [review]
Looks great :tada: :tada: 
-
Side note:  noticed commits from previous PRs are included, there is no harm with this but it looks cleaner  and helps with squashing  commits in merging- when to have only the new commits related to the new changes. Maybe you could consider this on future PRs?. A quick way to achieve this would be to create a new branch for each PR from the main branch or if you would like to continue working on the same branch, you could rebase your work branch with main before working on new changes [here](https://gist.github.com/cesswairimu/74804d644075fc423481cd405e2f4008)  are some rebase steps]

**Comment by jywarren** [comment]
Great work!!! TY for the review @cesswairimu !!

**Comment by 7malikk** [comment]
@cesswairimu 
Thanks a bunch, I will take your suggestions into consideration in other PRs.

Thank you @jywarren

**Comment by segun-codes** [comment]
> ## Looks great 🎉 🎉
> Side note: noticed commits from previous PRs are included, there is no harm with this but it looks cleaner and helps with squashing commits in merging- when to have only the new commits related to the new changes. Maybe you could consider this on future PRs?. A quick way to achieve this would be to create a new branch for each PR from the main branch or if you would like to continue working on the same branch, you could rebase your work branch with main before working on new changes [here](https://gist.github.com/cesswairimu/74804d644075fc423481cd405e2f4008) are some rebase steps]

Oh! @cesswairimu, many thanks. I will use this idea on subsequent contributions.

**Pull request merged**
