### PR TITLE
Fixed Geosearch Bar and Removed Duplicate Code

### LINKED ISSUE #1302: Fix Issue with Geosearch Bar and Remove Duplicate Code in archive.js
The search bar (on archive.html) fails to work each time the sidebar is closed (and remains in closed state) by clicking the tile. The duplicate of the code below should also be removed from the archive.js.
```
welcomeModal.addEventListener('hidden.bs.modal', (event) => {
  new bootstrap.Offcanvas(sidebar).show();
});
```
**Please describe the desired behavior.**
The geo-search bar on the page archive.html should work when the sidebar is closed by clicking the tile.

**Additional context (optional)**
See screenshot below for more details on the geocode search bar

screen-capture-_1_

### PR DESCRIPTION
**Pull request by segun-codes**
Fixes #1302 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [X] PR is descriptively titled 📑 and links the original issue above 🔗
* [X] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [X] code is in uniquely-named feature branch and has no merge conflicts 📁
* [X] screenshots/GIFs are attached 📎 in case of UI updates
* [X] @mention the original creator of the issue in a comment below for help or for a review

Screenshot below illustrates the proper functioning of the geosearch bar.

screen-capture-_2_

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by segun-codes** [comment]
Hi @jywarren, this PR is for you to review (and possibly, merge), many thanks!

This task is as agreed with @7malikk.

**Comment by segun-codes** [comment]
Hi @jywarren, reminder kindly review, many thanks!

**Comment by 7malikk** [comment]
Great job @segun-codes 

Concerning the extra commits check this comment by @cesswairimu out: https://github.com/publiclab/Leaflet.DistortableImage/pull/1292#pullrequestreview-1215653577
It helped me, cheers!

**Comment by segun-codes** [comment]
> 

Oh! @7malikk, many thanks for this. I will apply @cesswairimu's idea on subsequent contributions.

**Review by cesswairimu — APPROVED** [review]
Good catch!,Looks great :tada:

**Review by jywarren — APPROVED** [review]
Looks great, appreciate this fix!

**Comment by segun-codes** [comment]
> Looks great, appreciate this fix!

...many thanks!

**Pull request merged**
