### PR TITLE
Svg stack

### LINKED ISSUE #332: Inline SVG
We are currently using an external SVG sprite sheet to render our SVG's. In MK, this creates an issue with finding that external file because of some quirks with Rails asset path. 

To resolve this issue and ensure it doesn't happen in the future, I am thinking to just inline the SVG. 

This would be followed by a version bump and an attempt to reconnect back in MK and delete the extraneous overrwritten actions.

(And also relevant documentation updates ie. our wiki)

### LINKED ISSUE #343: Add border tool bound to "delete" action - bug?
I clicked the border button but got this notice -- maybe a small crossed wiring of these? Not a huge deal since there's a confirm alert but we should try to patch this pretty quick. Thanks!

image

### PR DESCRIPTION
**Pull request by sashadev-sky**
Fixes #332 (<=== Add issue number here)
- #330 (also took the few extra styles updated from #331 and update them here (sorry, I saw it after made the changes! Thought this way might be easier than rebasing there)
- Maybe fixes #343 - new toolbar instance is no longer being created to refresh toolbar icons (including in `toggleOutline`) so it wont be firing `toolbar:created`. Probably though, is not the problem bc other toolbar actions would have been causing the same issue
- version bump to `0.6.4`
- removed `svgforeverybody`
- stop running grunt svg plugins during build - instead created one grunt command too run both svg plugins (svgmin and svg_sprite): `grunt icons`
- stop including `xlmns` attribute for individual `symbol`s
- stop including `fill` attribute for individual `symbol`s
- updated SVG icon system wiki: https://github.com/publiclab/Leaflet.DistortableImage/wiki/SVG-Icon-System

Pending:
- update MK - check that #343 is fixed

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [ ] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@jywarren new svg stack here! Its going to be even easier to use than font awesome 👍👍. I created an `IconSet.js` file where all the `symbol` tags are located. When an instance of `L.EditAction` is initialized, the `symbol`s are all injected into the marker pane. 

Then I created another Toolbar option to pass, `svg: true`. Setting this allows the user to pass in just the `xlink:href` tag of the element, for ex. `#explore`, and within the class it will parse it into svg for them.

**Comment by sashadev-sky** [comment]
@jywarren now i'm just wondering if you could please help me understand caching and loading.

So since this is using a reference to an external asset anymore, there is no caching opportunity. And since this is a single JS page, everything really just has to only load once? The SVG is injected once and not removed afterwards. Is this the behavior we want? Or should I be injecting separate icon sets for `ControlBar` and `PopupBar` and adding / removing them according to which one is currently opened. Would that just be a performance downgrade by making it have to reinject every time ?

**Comment by sashadev-sky** [comment]
@rexagod looping ya in

**Comment by sashadev-sky** [comment]
@jywarren this is ready for merge! Can you give it a final review please?

**Comment by jywarren** [comment]
Looks awesome, thanks Sasha!!!

**Pull request merged**
