### PR TITLE
update first time issue template

### PR DESCRIPTION
**Pull request by leilayesufu**
Hi everyone, i tried creating a first time issue after solving mine, on going to the issue templates in the screenshot below, i discovered that there was no template for first time issues, on further inspection i discovered the first time issue template was present in the [Leaflet.DistortableImage](https://github.com/publiclab/Leaflet.DistortableImage)/.github as opposed to the [Leaflet.DistortableImage](https://github.com/publiclab/Leaflet.DistortableImage)/[.github](https://github.com/publiclab/Leaflet.DistortableImage/tree/main/.github)/ISSUE_TEMPLATE/ so i moved the file to the right folder
image

Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [ ] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by leilayesufu** [comment]
@TildaDares @jywarren 
Please kindly review

**Comment by TildaDares** [comment]
Hi @leilayesufu, instead of renaming the files, maybe we could create a file with the FTO template in the `ISSUE_TEMPLATE` folder. Thanks!

**Comment by leilayesufu** [comment]
Hi, @TildaDares 
Yes, that’s exactly what I did

**Comment by TildaDares** [comment]
Hi @leilayesufu, you deleted a file in https://github.com/publiclab/Leaflet.DistortableImage/pull/1122/commits/e5e1cb163acaac1c908b91b1e620be8f96824aaf

**Comment by leilayesufu** [comment]
Hii, @TildaDares 
Yes,
I deleted the old template that was in the wrong folder and created a new one in the right folder that’s the issues template folder with the exact same content

**Comment by TildaDares** [comment]
@leilayesufu You don’t have to delete that file. Please revert the change. Thank you!

**Comment by leilayesufu** [comment]
Oh, alright 
Do I close this pull request and do that and create a new one?

**Comment by TildaDares** [comment]
You should be able to revert a commit without having to close the PR.

**Comment by leilayesufu** [comment]
I have created the file back
Please kindly review

**Review by TildaDares — APPROVED** [review]
Amazing @leilayesufu. Thank you!

**Comment by leilayesufu** [comment]
Thank you so much!

**Pull request merged**
