### PR TITLE
Avg cm per pixel

### PR DESCRIPTION
**Pull request by sashadev-sky**
references #270  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updates
* [x] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@jywarren Let me know if this is ok!

Also, I don't know what is the reason for this but the dist file in the main repo has not been updating with the fto changes that refactored out a few functions into `EditHandle.js` (you can see these changes are still appearing as new updates in the dist file in my PR)

**Comment by jywarren** [comment]
Looks great! Ready to merge?

**Comment by sashadev-sky** [comment]
Yes 👍

**Comment by jywarren** [comment]
Awesome!

**Pull request merged**
