### PR TITLE
chore: 🤖 set up inital map view

### PR DESCRIPTION
**Pull request by PeculiarE**
Fixes #0000

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updates
* [x] @mention the original creator of the issue in a comment below for help or for a review

### CODE REVIEW

**Comment by jywarren** [comment]
This looks great, and it's a great place to begin. 🎉  I think the dist file may have been added by accident? Shall we keep this PR as just the HTML file?

**Comment by PeculiarE** [comment]
Thank you!

So, here's the thing. When I saw the dist file as part of my changes in my code editor, I was a bit puzzled because I believed that the contents  of the `dist` folder are not usually tracked on Github.

But then I checked the `.gitignore` file and saw that this particular dist file is one of two files in the `dist` folder that are actually being tracked:

https://github.com/publiclab/Leaflet.DistortableImage/blob/d6a9098ed46d08bb99bf15ca4378f678ea1c7d98/.gitignore#L8-L10

And even the pre-commit hook adds it as part of the files to be committed:

https://github.com/publiclab/Leaflet.DistortableImage/blob/d6a9098ed46d08bb99bf15ca4378f678ea1c7d98/package.json#L87-L93

So I'm a bit confused. Are these errors/oversights? Or am I missing something?

**Comment by PeculiarE** [comment]
Update: If both dist files are truly meant to be tracked, then in what instances should you actually let them be included in your commit or PR?

**Comment by jywarren** [comment]
Yes, we track dist files because we want them included in our npm package for direct inclusion in a web page, so users of our libraries don't have to run an extra "build" step before using them, and so we can guarantee we've tested the built dist file and it works. Not all projects do that, but maybe more should? But i see pros and cons 😄 

Here, I meant, since you haven't made any changes to the src folder, and no npm modules have updated, there shouldn't be a new dist file generated. However, there may be an exception because we've merged a number of Dependabot PRs, which have updated our node modules, some of which are built/baked into our dist files. So maybe that's what's happening? Regardless, since your project doesn't directly deal with those changes, I think it's simpler to not include the dist files since they aren't caused by anything you did. But if this is a simple PR we'll close quickly, and the code seems to work (in the existing examples), maybe it's just OK and we can include the dist files, since occasionally we do need to update our dist files with all the updated npm modules we've merged in. 

Usually this would just happen when there are more regular JS updates to the src folder, and recent npm modules would just get swept up with those. But we haven't changed much in src recently. 

Maybe a longer term idea would be to try to figure out a script to regenerate the dist files for each dependabot PR. But it sounds complicated! 😅 

So, your call - we can merge this if you're pretty sure these are just changes from dependabot updates, or we can exclude the dist files. Thanks for checking!!!

**Comment by PeculiarE** [comment]
Thanks for the detailed explanation, Jeff! It's way more clear to me now. And nope, I'm not 100% sure the changes are from dependabot 😅, so I've gone ahead to exclude the file from the PR.

**Comment by PeculiarE** [comment]
I would love to push the popup modal we talked about to this PR as well before we merge it. Thank you 😄!

**Comment by jywarren** [comment]
OK excellent, let's wait on the modal then. Let me know!

**Comment by PeculiarE** [comment]
Hi @jywarren!

The pop-up modal is ready, and I've pushed the latest changes.

Here's a brief snippet of how it looks like:

https://user-images.githubusercontent.com/75625011/184803737-e14c68b9-41d8-4287-b353-f14858e49ac7.mp4

**Comment by PeculiarE** [comment]
Oh, and I tried to convert one of the tasks on the checklist at #998 to an issue so I could link this PR to it, but it seems I do not have 'write' permissions on this repo. Can that be granted please @jywarren? Thank you!

**Review by jywarren — APPROVED** [review]
Look great! I added your permissions too. Thank you!!! ✨✨✨

**Comment by PeculiarE** [comment]
Thank you!!! I have now been able to create an issue for this from the list and link both together.

However, the PR title and the consequent merge commit message on the `main` branch don't reflect what the commit actually does. I've changed the title but since the merge has happened already, the commit message still remains the same.

Was wondering (if it's not too much trouble) if you could help amend the message to match with the PR's title? I saw a step-by-step tutorial in Github to do this (https://archive.org/details/texas-barnraising/) but since it's the `main` branch, I can't do it myself.

**Comment by jywarren** [comment]
I'll try resolving this today! Should be simple since no other commits have
been made and there are few or no other active contributors right now,
otherwise we'd have to warn people who might've pulled the latest commit.

**Comment by jywarren** [comment]
OK, done! Yeah, typically this can cause quite a bit of disruption if there are other users pulling regularly, but here it seems OK. I had to unlock the protection rules for a moment to do it, it wouldn't even allow me!

**Pull request merged**
