### PR TITLE
FEATURE: Expose toolbar action methods

### LINKED ISSUE #268: How to call methods (rotate, scale, lock, etc.) without toolbar and without hot keys ?
All is in title! ;) I need to use some customized external buttons to call plugin methods:
- Toggle image transparency
- Delete image
- Toggle image outline
- Lock / Unlock
- Rotate
- Scale
- Distort
- Export
- Change order...

Is there a simple way to do it?
Thanks,
:)

### PR DESCRIPTION
**Pull request by VladimirMikulic**
Methods exposed:
 - exportImage()
 - deleteImage()
 - toggleOrder()
 - toggleTransparency()
 - toggleOutline()
 - toggleLockMode()
 - lock()
 - unlock()

[Demo](https://streamable.com/1dazn)

This improvement is a part of the changes required for stable API.

Resolves #268 

@jywarren @sashadev-sky @SidharthBansal could you take a look at this, please?
Thanks.

### CODE REVIEW

**Comment by keshav234156** [comment]
@VladimirMikulic Haven't you claimed this issue in gci dasboard ?

**Comment by VladimirMikulic** [comment]
@keshav234156 yes, I did claim this task and @SidharthBansal approved it. He said I'll get points once this gets merged. @sashadev-sky was busy in the last 20 or so days, so to avoid blocked state that's what he did with all of us(not just me).

**Comment by keshav234156** [comment]
@VladimirMikulic Ok no worries!!

**Comment by SidharthBansal** [comment]
Yeah, I have to approve the tasks for the GCI students if the mentors are
busy so that they are out of blocked state. This is for all students IF PR
IS READY FROM STUDENT'S END.
Student may or may not get points for that task at the end of GCI depending
on the final evaluation of that task in GCI evaluation phase.

**Comment by sashadev-sky** [comment]
Also this would be a `hard` label.

**Comment by VladimirMikulic** [comment]
@sashadev-sky where should I start and what should I do? There are 2500+ lines of changes.
Do I need to rewrite the mode API?

**Comment by sashadev-sky** [comment]
@VladimirMikulic you woudn't need to rewrite the API but these two points have to be addressed:
1) ensure that only modes that are available on the image could be triggered via the method
2) ensuring that the modes won't update when the image is disabled

I think the modes API pr allowed addressing point 1, but yeah honestly would ignore it too much going on

**Comment by VladimirMikulic** [comment]
Thanks, @sashadev-sky!

**Pull request closed without merging**
