### PR TITLE
Suppresstb

### PR DESCRIPTION
**Pull request by sashadev-sky**
Fixes #349  (<=== Add issue number here)
#325 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [ ] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

===================

changes:
- `suppressToolbar` option added to collection as well, now the option only suppresses the toolbar for the actual class initializer its passed to
- fixed bug where markers don't show if toolbar is suppressed 
- bump to `0.7.6`

===================

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@rexagod @PanierAvide this PR has two fixes:
1) as pointed out by @PanierAvide, image markers should still render even if toolbar is suppressed
2) The collection group now has its own `supressToolbar` option to pass. (see README). 

Here is a gif:
1) Typical scenario - no suppressed toolbars:
sp

2) Scenario 2 - suppressed toolbars for individual images only:

sp2

3) Scenario 3 - suppressed for collection only - self explanatory

4) Scenario 4 - suppressed for images and collection: (This one will probably be your case @PanierAvide) 

sp4

**Comment by PanierAvide** [comment]
Thanks for this PR and all the details. You're correct my case is the fourth one.

**Comment by sashadev-sky** [comment]
@PanierAvide ok glad it helped! I willl merge this later today probably. Thank you for pointing out the bug!

**Comment by sashadev-sky** [comment]
@PanierAvide merging now :) Don't want to deter you from making PRs here in the future - definitely go for it and feel free to ask if you have any questions or suggestions about the code

**Comment by PanierAvide** [comment]
No worries :-) Thanks again for your work !

**Pull request merged**
