### PR TITLE
FEATURE: Make collection export option dynamic

### LINKED ISSUE #522: Make collection export option dynamic
If you run an export here with two images: https://sasha.mapknitter.org/examples/select.html, and then cancel it by clicking on the icon (just to save time), and then run a new export on only 1 image, you'll find that it still says exporting 2 / 2 images. 

Since we call 
https://github.com/publiclab/Leaflet.DistortableImage/blob/449ec1506fb3c1a3cb624be52be8c7ade6538216/src/edit/DistortableCollection.Edit.js#L320

and save it back into the opts object, the next time it wont recall it and will keep re-using the same group of images. 

quickest solution would be to just update the line to:
```
 opts.collection = this._group.generateExportJson();
``` 

but then custom collections wouldn't be possible anymore. 

Waiting to call the function until inside the method would also work, but there seems to be issues with the `this` binding so would have to fix that

### PR DESCRIPTION
**Pull request by VladimirMikulic**
[Demo](https://streamable.com/qdzw7)

Resolves #522 

@jywarren @sashadev-sky could you take a look at this? Thanks.

### CODE REVIEW

**Comment by VladimirMikulic** [comment]
Thanks, @sashadev-sky. I've updated the PR.
If the user passes custom `collection` property, it won't reset it in `cancelExport` or when the export is completed. On the other hand, if the user hasn't specified the `collection` property it will reset it.

**Comment by VladimirMikulic** [comment]
@sashadev-sky thank you! I apologise for committing Gruntfile changes, it's not efficient to run tests and linter on every change(I disable them in development). That's why I am trying to incorporate Webpack in this project :)

As you suggested I attached the `.images` to the `generateExportJson` function.
It's a good idea not forcing users to pass collection inside of a `.images` property.

In the end, I had the honour to bump package.json :tada:

**Comment by VladimirMikulic** [comment]
Thanks @sashadev-sky, I've implemented the required changes.

**Comment by VladimirMikulic** [comment]
@sashadev-sky anytime! More changes coming soon. :rocket:

**Comment by jywarren** [comment]
Oh my gosh already? My work over at https://github.com/publiclab/mapknitter/pull/1192 is moving faster now, and I'm almost ready. Can you bump the `package.json` version by 0.0.1 and I can publish a new version? Thank you!

**Comment by VladimirMikulic** [comment]
@jywarren are you referring to me or to @sashadev-sky?

**Comment by jywarren** [comment]
Either, actually! If you open a PR with the version bump then either Sasha or I can run `npm publish` after merging it. Thanks!

**Comment by VladimirMikulic** [comment]
#525 :)

**Comment by sashadev-sky** [comment]
@VladimirMikulic The task is on GCI so make sure to claim it at some point :)

**Comment by VladimirMikulic** [comment]
Thanks @sashadev-sky. I've seen it there. I'll claim it after the 'calculateProjectiveTransform test' gets approved :)

**Pull request merged**
