### PR TITLE
Refactored _calculateScalingFactor

### LINKED ISSUE #261: Refactor out `_calculateScalingFactor` function
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/Leaflet.DistortableImage/issues) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

We rewrite the same function, `_calculateScalingFactor` in a few of our files for each new "handle" class to have. Instead, we can define this function on `L.EditHandle`, the common class the other handle classes extend, and it will be available to all of them.

## Solution

**Where to find the relevant lines of code**: 

Delete the `_calculateScalingFactor` function from the following files:

1) 
https://github.com/publiclab/Leaflet.DistortableImage/blob/d91b2d7e946ae8ce064535dea8a0320683934b1f/src/edit/RotateHandle.js#L42-L54

2) 
https://github.com/publiclab/Leaflet.DistortableImage/blob/d91b2d7e946ae8ce064535dea8a0320683934b1f/src/edit/RotateScaleHandle.js#L58-L70

3) 
https://github.com/publiclab/Leaflet.DistortableImage/blob/d91b2d7e946ae8ce064535dea8a0320683934b1f/src/edit/ScaleHandle.js#L43-L55

4) Then, copy it into `src/edit/EditHandle.js` (you can add it as the last function defined on the `L.EditHandle` class).

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/Leaflet.DistortableImage](https://github.com/publiclab/Leaflet.DistortableImage)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, if there's an additional checklist provided for getting it merged, get those boxes checked off. Either way, mention me @sashadev-sky for a review.

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

### PR DESCRIPTION
**Pull request by yazicizuleyha**
Fixes #261  
Refactored out `_calculateScalingFactor` function and added it to `src/edit/EditHandle.js`

@sashadev-sky

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@yazicizuleyha this looks good! You seem to be having an error with Travis, it could be that your `package-lock.json` is corrupted. Try the following:

```
$ rm -rf package-lock.json node_modules
$ npm install
```

and then try committing again

**Comment by yazicizuleyha** [comment]
I did as you say, I hope I did it correctly :) @sashadev-sky

**Comment by sashadev-sky** [comment]
@yazicizuleyha it fixed error but the issue is you're not supposed to check in / commit the `package-lock.json`.. I will fix this for you and then show you what commands I used :)

**Comment by sashadev-sky** [comment]
@yazicizuleyha Ok so I have removed the `package-lock.json` from the PR by doing:
```
$ git checkout refactor-function

// Overwrite the modified file(s) with the file in another branch, let's consider it's main:
$ git checkout origin/main -- package-lock.json

$ git commit -m "Removed a modified file from pull request"
$ git push origin refactor-function
```
It's a little strange way to get it removed, but just note it down somewhere for whenever you might need it again :)

**Comment by sashadev-sky** [comment]
@yazicizuleyha When you force pushed that last time, you replaced all your work with just the deletion of the `package-lock.json`. You could get this work back, but i think in this scenario it will be easier for you to just redo it. Is that ok?

**just note before doing anything else**: from your feature branch you need to run `$ git pull https://github.com/publiclab/Leaflet.DistortableImage.git refactor-function` to pull in the updates made remotely here into your local repo.

Then you can redo the changes and commit normally and all should work out 👍

**Comment by yazicizuleyha** [comment]
@sashadev-sky Hi, i'm having a problem right now: I did as you say and pull, then made my changes again then push them. But i got an error saying that: 

> Updates were rejected because the tip of your current branch is behind

and want me to pull again. And when i pull again i have to redo all my work, which is cool and not a problem BUT then when i try to push, we're going back to square one :D

I don't know what to do anymore :D

**Comment by sashadev-sky** [comment]
@yazicizuleyha hmm have you tried `$ git push -f origin refactor-function`? I think this will allow you to  push your changes and ignore the warning

**Comment by yazicizuleyha** [comment]
I force pushed and it worked. Thank you :)

**Comment by sashadev-sky** [comment]
@yazicizuleyha great work!! I Just had to repeat the process I mentioned above for checking out the `package-lock.json` file. The Travis tests just passed so this is ready for merge 💜

**Pull request merged**
