### PR TITLE
Renamed L.MatrixUtil functions to match ES6

### LINKED ISSUE #599: Update L.MatrixUtil method creation to ES6 syntax
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/Leaflet.DistortableImage/issues) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

We just added support for ES6 in our library, and would like to start transitioning our code to use this syntax.

Let's update the method creation syntax in the `src/util/MatrixUtil.js` file from ES5 to ES6.

## Solution

**Where to find the relevant lines of code**: 

For the 7 functions in `src/util/MatrixUtil.js`, remove the `function` keyword and attach the method arguments to the method name instead.

Here is an example of how this will look for a different method. These ones should follow suit:

ES5
```JS
radiansToDegrees: function(angle) {
  return (angle * 180) / Math.PI;
},
```

ES6
```JS
radiansToDegrees(angle) {
  return (angle * 180) / Math.PI;
},
```

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/Leaflet.DistortableImage](https://github.com/publiclab/Leaflet.DistortableImage)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, if there's an additional checklist provided for getting it merged, get those boxes checked off. Either way, mention me @sashadev-sky for a review.

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

### PR DESCRIPTION
**Pull request by AkzharkynDM**
Fixes #599 

Renamed L.MatrixUtil functions to match ES6. Changed all functions in this file. 
Added dist files.

### CODE REVIEW

**Comment by AkzharkynDM** [comment]
@sashadev-sky  Could you please check this PR?

**Comment by sashadev-sky** [comment]
@AkzharkynDM this is perfect thank you! Would you mind just committing your dist file? this is a problem on our end not yours. if you enter `git status` you should see its still edited. That is the correct one you want (itll only show 2 changes as opposed to 14,000)

**Comment by AkzharkynDM** [comment]
@sashadev-sky Could you please verify if this is the correct dist file?

**Comment by sashadev-sky** [comment]
im thinking its because refactoring from ES5 -> ES6 doesnt translate to any update in the dist file

**Pull request merged**
