### PR TITLE
add: font awesome v4 CSS to Archive demo - archive.html

### LINKED ISSUE #1136: Add Fontawesome CSS to our Archive demo
We'd like to start using icons at https://publiclab.github.io/Leaflet.DistortableImage/examples/archive 

Let's add an include for FontAwesome v4 icons to the head!

https://fontawesome.com/v4/get-started/

I'd love if someone who recently completed a first-timers-only issue could take this up!

### PR DESCRIPTION
**Pull request by RealRichi3**
Fixes #1136 

## Summary
Added font awesome v4 CSS to head in archive.html

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updates
* [x] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by RealRichi3** [comment]
@jywarren please review

**Review by jywarren — APPROVED** [review]

**Comment by jywarren** [comment]
Well done! We would appreciate if you can help others take their next step as well!

**Comment by 7malikk** [comment]
@RealRichi3 Kindly ping me when you do create similar issues, as I'm eager to contribute. Thank you

**Comment by 7malikk** [comment]
Nice work on you merged PR @RealRichi3

**Pull request merged**
