### PR TITLE
Transfer js code in index.html into separate .js file

### LINKED ISSUE #1181: Transfer js code in index.html into separate .js file
index.html file currently contains Javascript code, this makes for a less readable and maintainable code especially as the codebase is set to become larger with more contributions from the community members. For this reason, it is important to transfer and maintain javascript code in a separate .js file different from the ./examples/index.html file as much as possible.

### PR DESCRIPTION
**Pull request by segun-codes**
Fixes #1181 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [X] PR is descriptively titled 📑 and links the original issue above 🔗
* [X] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [X] code is in uniquely-named feature branch and has no merge conflicts 📁
* [X] screenshots/GIFs are attached 📎 in case of UI updates
* [X ] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by segun-codes** [comment]
This PR transfers the javascript codes in index.html file into ` /examples/js/index.js`. The folder `js` is a new creation. It attempts to make the codes in .html files found in folder `/examples` more modular, readable and maintainable by separating control logic from UI concerns.

**Comment by segun-codes** [comment]
@jywarren @TildaDares, if you're okay with this PR, then at your direction, I can share a set of steps that first-timers (or you may decide) can follow to complete similar tasks on the other related open issues.  Thank you.

**Comment by jywarren** [comment]
Hello, I was thinking about this, and I think it's actually helpful for the more basic examples to have javascript inline, so it's all visible together. And these files have relatively short amounts of JavaScript. By contrast, the archive.html file has a lot, and has a much more complex and specific purpose, so I think it's going to be helpful to break out that code into different files. Does that make sense? Would you be willing to try doing this with the archive.html file?

**Comment by jywarren** [comment]
Wait, i'm now understanding that there are issues being created for each of these files. And I understand that the consistency of that is helpful. I've rethought this and I now agree that this makes sense. Sorry to go back and forth, i'm just trying to balance things. But I'm going to merge this now! Thank you!!!

**Comment by segun-codes** [comment]
> @jywarren @TildaDares, if you're okay with this PR, then at your direction, I can share a set of steps that first-timers (or you may decide) can follow to complete similar tasks on the other related open issues. Thank you.

@jywarren, thank you. What's your thought about the suggestion above

**Comment by vanithaak** [comment]
Hi @segun-codes , I think you mistakenly removed my code . Please add it again. Thanks!!

image

**Pull request merged**
