### PR TITLE
Undefined `call` condition

### LINKED ISSUE #236: Undefined method `call`
Race condition. Appears sometimes in Chrome Dev Tools:

Investigate condition occurrence on page load sometimes

```
Uncaught TypeError: Cannot read property 'call' of undefined
    at e._onKeyDown (leaflet.distortableimage.js:1460)
    at r (leaflet.js:5) 
```

### PR DESCRIPTION
**Pull request by rexagod**
Fixes #236 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by rexagod** [comment]
Just clarifying this here:
```js
  _onKeyDown: function(event) {
    var keymap = this.options.keymap,
      handlerName = keymap[event.which];

    if (this[handlerName] !== undefined && this._overlay.options.suppressToolbar !== true) {
      this[handlerName].call(this);
    }
  }
```

The `_onKeyDown` function initially listens for any `keydown`s and calls that respective function from the keymap that's appended to it. For eg., here `keymap` is our keymap object, `handlerName` can be `_toggleLock` and `this[handlerName]` is the particular function that it points to i.e., 

```js
function() {
    var map = this._overlay._map;

    map.removeLayer(this._handles[this._mode]);
    /* Switch mode. */
    if (this._mode === "lock") {
      this._mode = "distort";
      this._enableDragging();
    } else {
      this._mode = "lock";
      if (this.dragging) { this.dragging.disable(); }
      delete this.dragging;
    }

    map.addLayer(this._handles[this._mode]);
  }
```

**Comment by sashadev-sky** [comment]
@rexagod awesome! Will review this shortly

**Comment by sashadev-sky** [comment]
Ok no longer able to reproduce error. Really good debugging. @rexagod ready to merge on your confirmation

**Comment by rexagod** [comment]
Sure, please do! 👍

**Comment by sashadev-sky** [comment]
@rexagod ok cool, merged. Can you explain it to me a little further though? Why is it triggering on page load before any Keyboard events occur? And how did it pass the first undefined conditional?

**Comment by rexagod** [comment]
> The _onKeyDown function initially listens for any keydowns and calls that respective function from the keymap that's appended to it.

@sashadev-sky What this did was initiate a listener as soon as the "code was loaded" into the browser (no onload or onDOMloaded event attached to it) and therefore, this only occurred on first-time runs and hard-reloads since then there was no cache to source this from, so I just added a condition that checked the same, thus avoiding any first-time startup errors.

**Comment by sashadev-sky** [comment]
@rexagod ohh got it! So the issue is that some keydown was being read on page load, and that made `handlerName` pass the condition !== undefined. But then `this[handlerName]` was called which was undefined. So we add the `this[handlerName]` check there too. 

Now my question is, why does the keydown event trigger on page load? Was this error only happening if you reloaded the page by using a keyboard key and it caches that (if you hit refresh on the window, it wouldn't happen)? Or is something else going on

**Comment by rexagod** [comment]
> why does the keydown event trigger on page load?
@sashadev-sky The listener was initialized as soon as the code executed.
>Was this error only happening if you reloaded the page by using a keyboard key and it caches that
Doesn't matter if it's a keyboard key or not, it'll only occur if you do a hard reload for any number of reloads except the first (normal reloads won't work since the listener is now cached -- a typical async problem).

**Comment by sashadev-sky** [comment]
Ohhh ok I see. Thank you for explaining

**Comment by ChangXiaoning** [comment]
Hi, I am not a user of this library but a Node.js learner. From above conversation, I think the bug occurs when keydown event happens before page load event, right? I wonder why the 'this[handlerName]' equals to undefined if keydown event happens before page load event. Look forwards for your reply :). Thx.

**Pull request merged**
