### PR TITLE
auto-detect json from response refactor

### LINKED ISSUE #1343: Prompt user of saved map state
**Please describe the desired behavior.**
Describe the solution you'd like.
Include a prompt message informing the user that a JSON file has been detected in the response of supplied URL and also inquiring if the user would like to recover the saved map.

Place a filter for JSON files [here](https://github.com/publiclab/Leaflet.DistortableImage/blob/258cfb9e0edbaa3607eae6ebb2e67d7e2acb9c08/examples/js/archive.js#L142)
If items in each JSON file meet these requirements:
```
jsonFile.hasOwnProperty('nodes')  && jsonFile.nodes.length > 0 === true
jsonFile.hasOwnProperty('src') === true
```
If the files meet these requirements then trigger the aforementioned prompt

Upon the close of the prompt, invoke the map reconstruction

### PR DESCRIPTION
**Pull request by 7malikk**
Fixes #1343 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [x] code is in a uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updates
* [x] @mention the original creator of the issue in a comment below for help or for a review

### UI Changes
loadJSONFromRes

### CODE REVIEW

**Comment by 7malikk** [comment]
@jywarren This is ready for a merge, after which I'd make a PR for the save button refactor 
It goes the full circle 😃

**Review by jywarren — CHANGES_REQUESTED** [review]
Hi, just a couple small tweaks but this looks great!

**Comment by 7malikk** [comment]
All done @jywarren

**Review by jywarren — APPROVED** [review]

**Comment by jywarren** [comment]
Done and merged, great job!

**Pull request merged**
