### PR TITLE
Update remaining tests to correct class factory syntax

### LINKED ISSUE #190: Update remaining tests to correct class factory syntax
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/Leaflet.DistortableImage/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

**What's supposed to happen:**

In a previous FTO #182, initializing the L.Map class was updated to use the Leaflet libraries standard, shorter class factory syntax:

From the official [Leaflet](https://leafletjs.com/reference-1.0.0.html) docs:

<blockquote>
Class Factories

You may have noticed that Leaflet objects are created without using the new keyword. This is achieved by complementing each class with a lowercase factory method:

new L.Map('map'); // becomes:
L.map('map');
</blockquote>

Since testing is a form of documentation in addition to a way of ensuring stable functionality, we want to keep our tests consistent with our code syntax. Let's make updates to some test files to match this class factory syntax.

## Solution

**Where to find the relevant lines of code**: 

Remove the `new` keyword and change `L.Map` to `L.map` in the following code blocks:

1)
https://github.com/publiclab/Leaflet.DistortableImage/blob/2a70c099387fad4e5b7c84cf866ee55e787a7e20/test/src/DistortableCollectionSpec.js#L17

2)
https://github.com/publiclab/Leaflet.DistortableImage/blob/2a70c099387fad4e5b7c84cf866ee55e787a7e20/test/src/DistortableImageOverlaySpec.js#L9

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/Leaflet.DistortableImage](https://github.com/publiclab/Leaflet.DistortableImage)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, if there's an additional checklist provided for getting it merged, get those boxes checked off. Either way, mention me @sashadev-sky for a review.

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

### PR DESCRIPTION
**Pull request by shayna34**
Closes #190

### CODE REVIEW

**Comment by sashadev-sky** [comment]
@shayna34 Thank you for the PR! The main branch that this repo uses is actually named `main` not `master`. [master](https://github.com/publiclab/Leaflet.DistortableImage/tree/master) is 40 commits behind [main](https://github.com/publiclab/Leaflet.DistortableImage/tree/main) so that is why you are receiving this error.

Could you try pushing your updates to `main` instead? It might prompt you to create a new PR in which case I'll close this one.

@jywarren is this how you would recommend handling this?

**Comment by gauravano** [comment]
I changed the base of this PR from `master` to `main` but as @shayna34 has used master branch for the creation of their PR branch `correct-class-factory-syntax` the additional commits are also listed. 

I see three options here: 
1. Resetting to an old commit where master was in sync with main
2. Creating new PR after creating new branch from main
3. Creating new branch from main, do changes and make commit and then force-push on this branch using `git push origin branch1:branch2` where, branch1 - name of new branch and branch2 - name of branch you're pushing to (for your case, it would be `correct-class-factory-syntax`)

**Comment by sashadev-sky** [comment]
@gauravano how did you do that!! Also did not know step 3 was possible so thank you for teaching me that one! 

@shayna34 since this is your first issue here, go ahead and just create a new branch (step 2). The changes you made are very quick to redo so I would just redo them this time around. Then `git push origin main` and open a new PR. 

I think this is the simplest way and least likely to result in more PR debugging. But note that generally you always want to figure out how to fix your current PR instead of opening a new one. And maybe copy down the pointers @gauravano gave so you can try a different way if something similar happens again :)

Does that sound good?

**Comment by shayna34** [comment]
Thank you so much for the help @sashadev-sky and @gauravano! I will do step 2 and open a new PR. So sorry for the confusion!

**Comment by shayna34** [comment]
Created new PR #197!

**Comment by sashadev-sky** [comment]
@shayna34 Thank you so much! Closing this one.

**Comment by gauravano** [comment]
> @gauravano how did you do that!! Also did not know step 3 was possible so thank you for teaching me that one!

@sashadev-sky here's how base branch can be changed: 

change_base_git

Also, https://help.github.com/en/articles/changing-the-base-branch-of-a-pull-request

I have used the third one like one or two times myself but you can try that, I think it will work :)

**Comment by sashadev-sky** [comment]
woah thank you!

**Comment by sashadev-sky** [comment]
@gauravano Just double checked and realized I just don't have that view when I click edit. I think you have permissions I don't! 

also just rebased my branch on top of `master` by accident and was very concerned until I realized 😅

**Pull request closed without merging**
