### PR TITLE
ADD: Testing documentation

### LINKED ISSUE #506: Enhance testing documentation
In many of our other publiclab repos, there is extensive documentation on how to correctly test the codebase.
It is very difficult for someone not acquainted with the tech stack or the code itself to run the tests.
For example, if a user runs `npm test`, the command executed is:
`echo \"Error: no test specified\" && exit 1`.
This just returns an error but doesn't give the user any information on how he can actually specify a test to have it run. Instead we could link to our documentation.
 
What do you think?
Is this a good idea?

### PR DESCRIPTION
**Pull request by VladimirMikulic**
Testing is described in a new TESTING.md file.
I've also added `grunt test` to the `test` NPM script.

Resolves #506

@cesswairimu could you take a look at this? Thanks.

### CODE REVIEW

**Comment by jywarren** [comment]
This is really lovely. Wonderful work! cc @sashadev-sky @rexagod 🎉 💯

**Comment by jywarren** [comment]
Oh sorry @cesswairimu i just got excited!

cc @crisner @sagarpreet-chadha this is such a good documentation section on testing. take a look! 👀

**Comment by VladimirMikulic** [comment]
Thank you very much @jywarren!

**Comment by crisner** [comment]
This is great! Love the documentation. Amazing work @VladimirMikulic!

**Comment by VladimirMikulic** [comment]
Thanks @crisner.

**Comment by cesswairimu** [comment]
Amazing :rocket:

**Comment by VladimirMikulic** [comment]
I appreciate it @cesswairimu.

**Comment by sashadev-sky** [comment]
Just checked this out thank you so much!! @VladimirMikulic 

`$ mocha <filename>.js` doesn't work for me even after installing it globally. It doesn't recognize `L` (leaflet) as a context and after I managed to get that working by passing in some extra options it doesn't recognize `chai` from the `specHelper.js` file. Any clue what I'm missing?

**Comment by VladimirMikulic** [comment]
@sashadev-sky my mistake. I've noticed that we don't manually require modules in our tests.
In order for this to work, we should require chai in the test files, the same goes for L and other modules(browser's window object also).

That's one way of doing it. The other one is to wrap the code of the test file in one `describe.only()` block and then run npm test which will run only that test file.

How should I update this? Thanks.

**Comment by sashadev-sky** [comment]
@VladimirMikulic no problem! not a big deal. I'm not sure we can use require outside of the `Gruntfile` could be wrong? If we can't fix it the 1st way we can just update the readme to say the 2nd one! Thank you!

**Comment by VladimirMikulic** [comment]
@sashadev-sky we can use `require` outside of `Gruntfile`.

**Pull request merged**
