### PR TITLE
compartmentalize archive demo savedMaps into separate module

### PR DESCRIPTION
**Pull request by 7malikk**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [x] code is in a uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [x] @mention the original creator of the issue in a comment below for help or for a review

### CODE REVIEW

**Comment by 7malikk** [comment]
Hello @jywarren 
I moved the `savedMaps` modal to another file
but for some reason, the build is canceled

**Comment by jywarren** [comment]
Hmm, weird. I'll try re-running.

**Comment by 7malikk** [comment]
> Hmm, weird. I'll try re-running.

Alright

**Comment by jywarren** [comment]
Aha - they're trying to tell us that Ubuntu 18 won't be supported much longer:

```
This is a scheduled Ubuntu-18.04 brownout. The Ubuntu-18.04 environment is deprecated and will be removed on April 1st, 2023. For more details, see https://github.com/actions/runner-images/issues/6002
[build: .github#L1](https://github.com/publiclab/Leaflet.DistortableImage/pull/1360/files#annotation_9069805981)
The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002
```

we should use ubuntu-latest

**Comment by jywarren** [comment]
I changed it here! 

https://github.com/7malikk/Leaflet.DistortableImage/blob/70f70d0b62fecab4cbbdd154bf40a7c562249ef4/.github/workflows/build.yml#L5

**Comment by 7malikk** [comment]
Oh, alright 
Great! Thanks

**Review by jywarren — APPROVED** [review]
It looks like there was a formatter run; this is OK but if possible can you run that in a separate PR in the future so that it's easier to review just the contents and goals of this PR? Thank you! This looks good and if you've tested it out, we can merge once it passes!

**Comment by jywarren** [comment]
Great! Is it ready to merge? Let me know, great job!

**Comment by 7malikk** [comment]
> It looks like there was a formatter run; this is OK but if possible can you run that in a separate PR in the future so that it's easier to review just the contents and goals of this PR? Thank you! This looks good and if you've tested it out, we can merge once it passes!

Ohh, okay will do

**Comment by 7malikk** [comment]
@jywarren Yea it is merge ready

**Comment by jywarren** [comment]
Excellent!!

**Pull request merged**
