### PR TITLE
Removed function keyword from setMode, nextMode methods and updated t…

### PR DESCRIPTION
**Pull request by nicobelo91**
…he class factory function at the bottom of the file

Fixes #0000 (#737<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [x] @mention the original creator of the issue in a comment below for help or for a review
@sashadev-sky how do I add a screenshot to a PR body?

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by nicobelo91** [comment]
@sashadev-sky, why could it be that the checks haven't been completed yet?

**Review by SMAKSS — APPROVED** [review]
Thanks for the PR! Looks good to me. 😉

**Comment by nicobelo91** [comment]
@SMAKSS no problem! Thanks for letting me participate!

**Review by sashadev-sky — APPROVED** [review]
@nicobelo91 

Thank you!! This is great, will merge this now. 

Few PR tips for future references:
1. You are meant to replace the #0000 with the issue # in the PR body. This way the linked issue will close once this PR is merged.
2. Title does not have to be so specific can just say ES6 upgrades in DistortableImage.Edit class or something

The Travis build happens occasionally. It confuses me a bit too but if you visit the [commit link(https://github.com/publiclab/Leaflet.DistortableImage/pull/766/commits/f85f421765937507c4ecfb8a319ae8fd27972875) you'll find it says "This commit does not belong to any branch on this repository." To fix this you have to rebase over main and force push - or the queued test will be there forever.

Anyway it's fine to merge without doing this this time.

**Pull request merged**
